-- Table: CLIENTE_DESCAUT
CREATE TABLE CLIENTE_DESCAUT (PERDESCONTO, CODCLIENTE, DESCFINANVLTOTNOTA);
-- Table: RELACAOCSTPISSAIDAENTRADA
CREATE TABLE RELACAOCSTPISSAIDAENTRADA (ID, CSTPISENTRADA, CSTPISSAIDA, CODEMPRESA);
-- Table: NIVEL_TPPEDIDO
CREATE TABLE NIVEL_TPPEDIDO (CODNIVEL, IDTPPEDIDO, CODIGO);
-- Table: LOGALTERACAOSEGNIVELACESSO
CREATE TABLE LOGALTERACAOSEGNIVELACESSO (CODIGO, ABRIRROTINASCOMEMMPRESASLIBERADASSELECIONADAS_ALT, ABRIRROTINASCOMEMMPRESASLIBERADASSELECIONADAS_ANT, CADASTROEMPRESAEDITAR_ALT, CADASTROEMPRESAEDITAR_ANT, CADASTROEMPRESAINCLUIR_ALT, CADASTROEMPRESAINCLUIR_ANT, CODCAIXABANCO_ALT, CODCAIXABANCO_ANT, CODEMPRESASPERMITIDAS_ALT, CODEMPRESASPERMITIDAS_ANT, CODFUNCALT, CODMOEDA_ANT, CODMOEDA_ALT, CODNATUREZAOPERACAO_ALT, CODNATUREZAOPERACAO_ANT, CODTIPODEPEDIDO_ALT, CODTIPODEPEDIDO_ANT, CODUSUARIOALT, DATAALTERACAO, PERMITEACESSOCHECKOUT_ALT, PERMITEACESSOCHECKOUT_ANT, PERMITEACRECIMOACERTOCAIXA_ALT, PERMITEACRECIMOACERTOCAIXA_ANT, PERMITEACRECIMO_ANT, PERMITEACRECIMOPEDIDODEVENDA_ALT, PERMITEACRECIMOPEDIDODEVENDA_ANT, PERMITEACRECIMO_ALT, PERMITEACRESACERTOCAIXA_ALT, PERMITEACRESACERTOCAIXA_ANT, PERMITEALTERARCOBRANCAACERTOCAIXA_ALT, PERMITEALTERARCOBRANCAACERTOCAIXA_ANT, PERMITEALTERARCOBRANCAVENCIMENTO_ALT, PERMITEALTERARCOBRANCAVENCIMENTO_ANT, PERMITEALTERARCUSTO804_ALT, PERMITEALTERARCUSTO804_ANT, PERMITEALTERARLIMITEDECREDITO_ALT, PERMITEALTERARLIMITEDECREDITO_ANT, PERMITEALTERARNUMCHEQUE_ALT, PERMITEALTERARNUMCHEQUE_ANT, PERMITEALTERARPEDIDOCOMSTATUSLIBERADO_ALT, PERMITEALTERARPEDIDOCOMSTATUSLIBERADO_ANT, PERMITEALTERARPLANODECONTASESTOQUE_ALT, PERMITEALTERARPLANODECONTASESTOQUE_ANT, PERMITEALTERARPLANODECONTASNODESDOBRAMENTO_ALT, PERMITEALTERARPLANODECONTASNODESDOBRAMENTO_ANT, PERMITEALTERARTRIBUTNASAIDA_ALT, PERMITEALTERARTRIBUTNASAIDA_ANT, PERMITEALTERARUSUARIOESENHADOCOLABORADOR_ALT, PERMITEALTERARUSUARIOESENHADOCOLABORADOR_ANT, PERMITEALTERARVENDEDORGESTAO_ALT, PERMITEALTERARVENDEDORGESTAO_ANT, PERMITEALTERARVENDEDORPEDIDODEVENDA_ALT, PERMITEALTERARVENDEDORPEDIDODEVENDA_ANT, PERMITEALTORIZARNEGOCIACAO_ALT, PERMITEALTORIZARNEGOCIACAO_ANT, PERMITEAUTORIZARPAGAMENTOCP_ALT, PERMITEAUTORIZARPAGAMENTOCP_ANT, PERMITEBAIXACRECEBER_ALT, PERMITEBAIXACRECEBER_ANT, PERMITEBAIXACP_ALT, PERMITEBAIXACP_ANT, PERMITEBAIXAPARCIAL_ALT, PERMITEBAIXAPARCIAL_ANT, PERMITEBAIXAPARCIALCP_ALT, PERMITEBAIXAPARCIALCP_ANT, PERMITEBLOQUEARDESBLOQUEARCLIENTE_ALT, PERMITEBLOQUEARDESBLOQUEARCLIENTE_ANT, PERMITEBLOQUEARDESBLOQUEARESTOQUE_ALT, PERMITEBLOQUEARDESBLOQUEARESTOQUE_ANT, PERMITECANCCHECKOUT_ALT, PERMITECANCCHECKOUT_ANT, PERMITECANCELARBOLETONA616_ALT, PERMITECANCELARBOLETONA616_ANT, PERMITECANCELARCONFERENCIADEENTRADA_ALT, PERMITECANCELARCONFERENCIADEENTRADA_ANT, PERMITECANCELARCONFERENCIADESAIDADEUMPEDIDO_ALT, PERMITECANCELARCONFERENCIADESAIDADEUMPEDIDO_ANT, PERMITECANCELARNOTAENTRADA_ALT, PERMITECANCELARNOTAENTRADA_ANT, PERMITECANCELARPEDIDONA302_ALT, PERMITECANCELARPEDIDONA302_ANT, PERMITECANCELARVENDABALCAO_ALT, PERMITECANCELARVENDABALCAO_ANT, PERMITECORTENOCARREGAMENTOESTOQUE_ALT, PERMITECORTENOCARREGAMENTOESTOQUE_ANT, PERMITECRIARNEGOCIACAOPORPERIODO_ALT, PERMITECRIARNEGOCIACAOPORPERIODO_ANT, PERMITEDESDCRECEBER_ALT, PERMITEDESDCRECEBER_ANT, PERMITEDESCONTOACERTOCAIXA_ALT, PERMITEDESCONTOACERTOCAIXA_ANT, PERMITEDESCONTOAUTOMATICONAVENDA_ALT, PERMITEDESCONTOAUTOMATICONAVENDA_ANT, PERMITEACESSOAOCHECKOUT_ALT, PERMITEDESCCHECKOUT_ANT, PERMITEDESCONTOCP_ALT, PERMITEDESCONTOCP_ANT, PERMITEDESCONTOCONTROLEDERECEBIMENTO_ALT, PERMITEDESCONTOCONTROLEDERECEBIMENTO_ANT, PERMITEDESCONTOENTRADADANOTAFISCAL_ALT, PERMITEDESCONTOENTRADADANOTAFISCAL_ANT, PERMITEDESCONTORODAPE_ALT, PERMITEDESCONTORODAPE_ANT, PERMITEDESDOBRAMENTOACERTOCAIXA_ALT, PERMITEDESDOBRAMENTOACERTOCAIXA_ANT, PERMITEESTORNARBAIXARCREDITODOCLIENTENA605_ALT, PERMITEESTORNARBAIXARCREDITODOCLIENTENA605_ANT, PERMITEDESDOBRAR_ALT, PERMITEESTORNARCP_ANT, PERMITEESTORNOCRECEBER_ALT, PERMITEESTORNOCRECEBER_ANT, PERMITEEXIBIRVENDASAPENASDOVENDEDORLOGADO_ALT, PERMITEEXIBIRVENDASAPENASDOVENDEDORLOGADO_ANT, PERMITEEXPORTARRELATORIOS_ALT, PERMITEEXPORTARRELATORIOS_ANT, PERMITEFINANCEIRONEGOCIADO_ALT, PERMITEFINANCEIRONEGOCIADO_ANT, PERMITEIMPRIMIRPRECOMEDIO_ALT, PERMITEIMPRIMIRPRECOMEDIO_ANT, PERMITEJURO_ALT, PERMITEJURO_ANT, PERMITEJUROCP_ALT, PERMITEJUROCP_ANT, PERMITELIBERARPEDIDO_ALT, PERMITELIBERARPEDIDO_ANT, PERMITEPRECIFICACAO_ALT, PERMITEPRECIFICACAO_ANT, PERMITEREIMPRESSAODECREDITO_ALT, PERMITEREIMPRESSAODECREDITO_ANT, PERMITEREIMPRIMIRLISTADECARREGAMENTO_ALT, PERMITEREIMPRIMIRLISTADECARREGAMENTO_ANT, PERMITEREPLICARDADOSPARAOPRODUTO_ALT, PERMITEREPLICARDADOSPARAOPRODUTO_ANT, PERMITEREPLICARTRIBUTACAO_ALT, PERMITEREPLICARTRIBUTACAO_ANT, PERMITEREQUISICAOESTOQUE_ALT, PERMITEREQUISICAOESTOQUE_ANT, PERMITETRANSFVENDADEVENDEDOR_ALT, PERMITETRANSFVENDADEVENDEDOR_ANT, PERMITETRANSFERENCIADEDEPOSITOESTOQUE_ALT, PERMITETRANSFERENCIADEDEPOSITOESTOQUE_ANT, PERMITEVISUALIZARQTPEDIDANACONFERENCIADEENTRADA_ALT, PERMITEVISUALIZARQTPEDIDANACONFERENCIADEENTRADA_ANT, USAPRODUCAOPUXADA_ALT, USAPRODUCAOPUXADA_ANT, PERMITEALTERARENTRADA_ANT, PERMITEALTERARENTRADA_ALT, PERMITEALTERARPESSOA_ALT, PERMITEALTERARPESSOA_ANT);
-- Table: CXBANCO_COMPLEMENTOS
CREATE TABLE CXBANCO_COMPLEMENTOS (CONTAGARANTIDA, TIPODESCONTOBOLETO, CODCXBANCO, CODCONTACONTABIL, CODCXBANCOPRINC, INSTFINANCPGTOELETRONICO);
-- Table: COBCLI
CREATE TABLE COBCLI (CODCLIENTE, CODCOBRANCA);
-- Table: NIVELACESSO
CREATE TABLE NIVELACESSO (ID, CODCOLABORADOR);
-- Table: LOGALTLIMITECRED
CREATE TABLE LOGALTLIMITECRED (ID, DTALTERACAO, VLLIMITEALTERADO, VLLIMITEANTERIOR, CODCLIENTE, CODFUNCALT);
-- Table: CXBANCOBOLETOWS
CREATE TABLE CXBANCOBOLETOWS (CLIENTEID, PATHARQCRT, PATHARQKEY, SECRETID, CODCXBANCO);
-- Table: COBRANCA
CREATE TABLE COBRANCA (CODCOBRANCA, CHAMATEF, CODPGTO, DESCRICAO, DIASBLOQAUT, DIASFLUXO, ISCHECKOUT, STATUSFV, TIPOCOBRANCA, CODPLANOPGTOPADRAO);
-- Table: REMESSA
CREATE TABLE REMESSA (ID, DESCREMESSA, DTREMESSA, NUMREMESSA, PATHREMESSA, QTTITULOS, VLTOTAL, CODCXBANCO, CODFUNCLANC);
-- Table: LOGALTPARAM
CREATE TABLE LOGALTPARAM (ID, ALTERACAO, CODFUNCALT, DTALTERACAO, PARAMETRO);
-- Table: CXBANCOMATERA
CREATE TABLE CXBANCOMATERA (CHAVEPIXRETIRADA, NUMDIASINICIAJURO, NUMDIASPROTESTO, PATHPDFPIXCOB, PERJURO, PERMULTA, CODCXBANCO, CODCXBANCORETIRADA);
-- Table: COBRANCA_COMPLEMENTOS
CREATE TABLE COBRANCA_COMPLEMENTOS (DTULTALTERACAO, VLMINIMOVENDA, CODCOBRANCA, DISPONIVELPARAVENDA, CODFUNCALT, ADIANTCOBRANCA, INTEGRACAOMATERA);
-- Table: REQUISICAOCOMPRA
CREATE TABLE REQUISICAOCOMPRA (NUMREQUISICAO, DTCANCELAMENTO, DTREQUISICAO, DTULTALTERACAO, MOTIVOCANC, OBSERVACAO, QTITENS, STATUS, TOTPESOBRUTO, TOTPESOLIQUIDO, CODFUNCALTERACAO, CODFUNCCANC, CODFUNCLANC, CODEMPRESA);
-- Table: OBRIGACOESICMSREC
CREATE TABLE OBRIGACOESICMSREC (CODIGO, DESCRICAO);
-- Table: LOGALTPEDCOMPRA
CREATE TABLE LOGALTPEDCOMPRA (CODIGO, CODFUNCALT, CODPRODUTO, DTALT, NUMPEDIDO, QTALT, QTPEDIDA, STATUS, TIPOALT);
-- Table: CXBANCOPIXCD
CREATE TABLE CXBANCOPIXCD (CHAVEPIX, CLIENTEID, DEVELOPERAPPLICATIONKEY, PATHARQCERTIFICADO, PATHARQCHAVEPRIVADA, SECRETID, SENHAARQPFX, TIPOCHAVE, CODCXBANCO);
-- Table: CODAJAPURICMS
CREATE TABLE CODAJAPURICMS (CODIGO, DESCRICAO, DTFIM, DTINICIO);
-- Table: ROTA
CREATE TABLE ROTA (CODIGO, ROTA);
-- Table: OBSLANCFISCAL
CREATE TABLE OBSLANCFISCAL (NUMLANCAMENTO, DESCRICAO);
-- Table: LOGALTPESSOA
CREATE TABLE LOGALTPESSOA (ID, CONTANTERIOR, DTALTERACAO, NUMCAMPO, CODFUNCALT, CODPESSOA);
-- Table: CXPDV
CREATE TABLE CXPDV (CODIGO, IDTERMINAL, NUMCAIXA, NUMSERIEMB, OBSERVACAO, SERIENFCE, ULTNUMNFCE, CODCAIXABANCO, CODEMPRESA, ULTNUMNFCE2);
-- Table: CODAJDOCFISCAL
CREATE TABLE CODAJDOCFISCAL (CODIGO, DESCRICAO, DTFIM, DTINICIO);
-- Table: ROTEIRIZACAOVENDEDOR
CREATE TABLE ROTEIRIZACAOVENDEDOR (CODIGO, DIASEMANA, DTROTEIRIZACAO, ENDERECO, LATITUDE, LONGITUDE, POSICAO, CODCLIENTE, CODVENDEDOR);
-- Table: ORACULO_USUARIO_EMPRESAS
CREATE TABLE ORACULO_USUARIO_EMPRESAS (CODUSUARIO, CODEMPRESA);
-- Table: ORACULONOTIFICACAO
CREATE TABLE ORACULONOTIFICACAO (CODIGO, DESCRICAO, NOTIFICACAO, TEMPORALNOTIFICACAO, TIPONOTIFICACAO);
-- Table: LOGALTPRODUTO
CREATE TABLE LOGALTPRODUTO (ID, CONTANTERIOR, DTFIM, DTINICIO, NUMCAMPO, CODFUNCALT, CODPRODUTO);
-- Table: CODBCCREDPISCOFINS
CREATE TABLE CODBCCREDPISCOFINS (CODIGO, DESCRICAO, DTFIM, DTINICIO);
-- Table: ROTERIZACAOCARREGAMENTO
CREATE TABLE ROTERIZACAOCARREGAMENTO (CODIGO, DTROTERIZACAO, ENDERECO, LATITUDE, LONGITUDE, POSICAO, NUMCARGA, NUMNFSAIDA);
-- Table: ORACULOUSUARIO
CREATE TABLE ORACULOUSUARIO (CODIGO, DTULTSOLICITACAO, ATIVO, CODUSUARIO);
-- Table: LOGBACKUP
CREATE TABLE LOGBACKUP (CODIGO, DTBACKUP, NOMEARQUIVO, PATH);
-- Table: CXPDV_COMPLEMENTOS
CREATE TABLE CXPDV_COMPLEMENTOS (BITSDADOSBALANCAPESO, DTULTALTERACAO, IMPLISTASEPARACAO, PORTABALANCAPESO, TIPOBALANCAPESO, CODCXPDV, ADMCARTAO, CODFUNCALTERACAO, EXIBIRQRCODEPIX, TIPOSERVICOPDV, IMPRIMIRCOMPROVANTENFC2);
-- Table: CODBCCREDPISCOFINS_CFOP
CREATE TABLE CODBCCREDPISCOFINS_CFOP (CODIGO, CODOPERACAO);
-- Table: ROTINA
CREATE TABLE ROTINA (CODIGO, ATIVO, CODROTINA, CRIPTOGRAFIA, NOME, LINKVIDEOAULA);
-- Table: ORACULOUSUARIONOTIFICACAO
CREATE TABLE ORACULOUSUARIONOTIFICACAO (DTULTIMAEXECUCAO, HORARIO, ATIVO, CODUSUARIO, CODNOTIFICACAO);
-- Table: LOGBLOQUEIODESBLOQUEIO
CREATE TABLE LOGBLOQUEIODESBLOQUEIO (ID, DTALTERACAO, MOTIVO, STATUS, CODCLIENTE, CODFUNCALT);
-- Table: DECIMPORTACAO
CREATE TABLE DECIMPORTACAO (ID, DDI, DDESEMB, LOCALDESEMBARACO, NDI, TPINTERMEDIO, TPVIATRANSP, VLAFRM, IDMOV, UFDESEMB);
-- Table: CODBENEFICIOFISCAL
CREATE TABLE CODBENEFICIOFISCAL (CODBENEF, BENEFICIO, DESCRICAO, DTFINAL, DTINICIO, DTULTALTERACAO);
-- Table: SECAO
CREATE TABLE SECAO (CODSECAO, DESCRICAO, CODDEPARTAMENTO, DTULTALTERACAO);
-- Table: ORIGEMMERCADORIA
CREATE TABLE ORIGEMMERCADORIA (ID, CODIGO, DESCRICAO);
-- Table: LOGCANCBOL
CREATE TABLE LOGCANCBOL (ID, CODFUNCCANC, DTCANC, NOSSONUMERO, NUMNOTA, NUMSAIDA);
-- Table: DEMAISDOCSPISCOFINS
CREATE TABLE DEMAISDOCSPISCOFINS (ID, ALIQCOFINS, ALIQPIS, CODCCUS, CODCTA, CODITEM, CODPART, CSTCOFINS, CSTPIS, DESCDOCOPER, DTOPER, INDOPER, INDORIGCRED, NATBCCRED, VLBCCOFINS, VLBCPIS, VLCOFINS, VLOPER, VLPIS, CODEMPRESA);
-- Table: CODINFADICIONALICMS
CREATE TABLE CODINFADICIONALICMS (CODIGO, DESCRICAO, DTFIM, DTINICIO);
-- Table: SEGNIVELACESSO
CREATE TABLE SEGNIVELACESSO (CODNIVELACESSO, CANCNOTAENTRADA, CANCVENDABALCAO, PERMITEACRESACERTOCAIXA, PERMITEACRESENTRADA, PERMITEACRESSAIDA, PERMITEALTERARPRECIFICACAO, PERMITEALTERARUSUARIOPESSOA, PERMITEALTERARVENDEDORPESSOA, PERMITEALTTRIBUTSAIDA, PERMITEALTERARCOBRANCA, PERMITEALTERARLIMITE, PERMITEALTERARVENDEDOR, PERMITEBAIXACPAGAR, PERMITEBAIXACRECEBER, PERMITEBAIXAPARCIAL, PERMITEBLOQUEARCLIENTE, PERMITECANCCHECKOUT, PERMITECORTECARGA, PERMITEDESCACERTOCAIXA, PERMITEDESCCPAGAR, PERMITEDESCCRECEBER, PERMITEDESCENTRADA, PERMITEDESCRODAPE, PERMITEDESCSAIDA, PERMITEDESCCHECKOUT, PERMITEDESDCPAGAR, PERMITEDESDCRECEBER, PERMITEESTORNOCPAGAR, PERMITEESTORNOCRECEBER, PERMITEFINNEGOCIADO, PERMITEJUROCPAGAR, PERMITEJUROCRECEBER, PERMITELIBERARPEDIDO, PERMITEREEMPRIMIRCARG, PERMITEREPLICARTRIBUTACAO, PERMITEREQUISICAO, PERMITETRANSFERENCIA, CODFUNCIONARIO, PERMITEALTERARCOBRANCAACERTO, PERMITEDESDOBRARACERTO, MOSTRAAPENASVENDLOG, PERCMAXDESCRODAPE, PERCMAXDESCRODCHECKOUT, PERMITEALTPLCONTAS, PERMITEAUTORIZARPAGAMENTO, PERMITEREIMPCRED, PERMITEDESCAUT, PERMITEMULTQT, PERMITEFINALIZARPEDCOMPRA);
-- Table: OSINVENTARIO
CREATE TABLE OSINVENTARIO (NUMINVENTARIO, DTCANCELAMENTO, DTFECHAMENTO, DTFIM, DTINICIO, DTINVENTARIO, MOTIVOCANC, NUMCONTAGEM, OBSERVACAO, STATUS, CODEMPRESA, CODFUNCCANCELAMENTO, CODFUNCFECHAMENTO, CODFUNCLANCAMENTO);
-- Table: LOGCOMBOVENDA
CREATE TABLE LOGCOMBOVENDA (CODIGO, CODPRODCOMBO, NUMPEDIDO, NUMSAIDA, QTPEDIDA);
-- Table: DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (CODDEPARTAMENTO, DESCRICAO, DTULTALTERACAO, ENVIARB2B, NOMEICONEB2B);
-- Table: CODMOTRESTCOMPICMS
CREATE TABLE CODMOTRESTCOMPICMS (CODAJUSTE, DESCRICAO, DTFINAL, DTINICIO, DTULTALTERACAO);
-- Table: SEGNIVELACESSO_COMPLEMENTO
CREATE TABLE SEGNIVELACESSO_COMPLEMENTO (PERMITEALTERAREMPRESA, PERMITEEXPORTADADOS, PERMITEINCLUIREMPRESA, CODUSUARIO, PERMITEIMPRIMIRPRECOMEDIO, ABRIRMULTIEMPSELEC, PERMITEACESSOCHECKOUT, ALTPLANOCONTASDESD, PERMITEALTERARCUSTO804, PERMITEALTERARNUMCHEQUE, PERMITEALTERARPEDIDOLIBERADO, PERMITEAUTORIZARNEGOCIACAO, PERMITEBAIXAPARCIALCP, PERMITEBAIXARESTORCREDCLIENTE, PERMITEBLOQDESBLOQESTOQUE, PERMITECANCELARBOLETOS, PERMITECANCCONFENTRADA, PERMITECANCCONFPEDIDO, PERMITECANCPEDIDO302, PERMITECRIARNEGOCIACAOPORPERIODO, PERMITEREPLICARDADOSPRODUTO, PERMITETRANSFVENDAVENDEDOR, PERMITEVISUALIZARQTPEDIDACONFENTRADA, USAPRODPUXADA, ALTCOBCPAGAR, PERMITEALTERARENTRADA, PERMITEALTERARPESSOA, PERMITECANCRECEITADESPESA, PERMITECANCELARINUTILIZAR305, PERMITECONCILIACAOSITEF, PERMITEFATURARCARGA, PERMITEFECHARENTREGACARGA, PERMITEALTERARCOMPOSICAOCPV);
-- Table: OSINVENTARIOITENS
CREATE TABLE OSINVENTARIOITENS (CODIGO, DTLANCCONT1, DTLANCCONT2, DTLANCCONT3, QTCONT1, QTCONT2, QTCONT3, QTDIF1, QTDIF2, QTDIF3, QTESTOQUECONT1, QTESTOQUECONT2, QTESTOQUECONT3, VLCUSTOMEDIOCONT1, VLCUSTOMEDIOCONT2, VLCUSTOMEDIOCONT3, VLCUSTOULTENTRADACONT1, VLCUSTOULTENTRADACONT2, VLCUSTOULTENTRADACONT3, CODFUNCLANCONT1, CODFUNCLANCONT2, CODFUNCLANCONT3, CODEMPRESA, NUMINVENTARIO, CODPRODUTO);
-- Table: LOGCOMBOVENDAITENS
CREATE TABLE LOGCOMBOVENDAITENS (CODIGO, CODITEMPED, CODMOV, CODPRODCOMBO, QTPEDIDA, CODCOMBOVENDA);
-- Table: DESCARGAMDFE
CREATE TABLE DESCARGAMDFE (ID, CODCIDADE, NUMMDFE);
-- Table: CODRECEITACONTCOFINS
CREATE TABLE CODRECEITACONTCOFINS (CODIGO, DESCRICAO, DTFIM, DTINICIO, PERIODICIDADE);
-- Table: SEGUROMDFE
CREATE TABLE SEGUROMDFE (ID, CNPJRESP, CNPJSEG, NOMESEG, NAPOL, NAVER, RESPSEG, NUMMDFE);
-- Table: OUTROSDOCSPISCOFINS
CREATE TABLE OUTROSDOCSPISCOFINS (ID, ALIQCOFINS, ALIQPIS, CODCCUS, CODCTA, CODITEM, CODPART, CSTCOFINS, CSTPIS, DESCDOCOPER, DTOPER, INDORIGCRED, INDOPER, NATBCCRED, VLBCCOFINS, VLBCPIS, VLCOFINS, VLOPER, VLPIS, CODEMPRESA);
-- Table: LOGCONVERSAONFCE2
CREATE TABLE LOGCONVERSAONFCE2 (ID, CODCXPDV, DTLANCAMENTO, NUMNOTANFCE2, NUMNOTANFCE65, STATUSENVIOCHECKOUT);
-- Table: DESCONTOQUANTIDADE
CREATE TABLE DESCONTOQUANTIDADE (ID, PERDESCONTO, QUANTFINAL, QUANTINICIO, CODEMPRESA, CODPRODUTO, DTULTALTERACAO, STATUS, CODTABELA);
-- Table: CODRECEITACONTPIS
CREATE TABLE CODRECEITACONTPIS (CODIGO, DESCRICAO, DTFIM, DTINICIO, PERIODICIDADE);
-- Table: SEMAFORO
CREATE TABLE SEMAFORO (ID, CAMPOTABELA, CODROTINA, DESCMETODO, DTLOCK, DTUNLOCK, IDTABELA, LOCK, TABELA, TIPOSEMAFORO, USUARIO);
-- Table: PAIS
CREATE TABLE PAIS (CPAIS, NOMEPAIS);
-- Table: LOGCORTE
CREATE TABLE LOGCORTE (CODIGO, CODFUNCCORTE, CODPRODUTO, DTCORTE, NUMPEDIDO, QTCORTE, QTSEPARADA, VLCORTE);
-- Table: DETBCCREDITOCOFINS
CREATE TABLE DETBCCREDITOCOFINS (ID, CSTCOFINS, DESCCRED, DTFIM, DTINICIO, NATBCCRED, QUANTBCCOFINS, QUANTBCCOFINSTOT, VLBCCOFINS, VLBCCOFINSCUM, VLBCCOFINSNC, VLBCCOFINSTOT, VLBCTOTCSTALIQ, CODEMPRESA);
-- Table: CODRECEITAICMS
CREATE TABLE CODRECEITAICMS (CODIGO, CODREC, DESCCOD, DTFIM, DTINICIO, UF);
-- Table: SETOR
CREATE TABLE SETOR (CODIGO, NOME);
-- Table: PARAMETRO
CREATE TABLE PARAMETRO (CODIGO, ABATERIMOBINVESTRESULTLIQUIDO, PEDIDOCLIENTEBLOQUEADOFV, PEDIDOSEMESTOQUEFV, PEDIDOCLIENTESEMLIMITEFV, VENDASEMESTOQUE, EDITAPRECOVENDA, ISDATSERVAL, MENSAGEMEMAIL, PATHBACKUP, PORTASMTP, QTDECIMAIS, REGIMECAIXA, REGIMECOMPETENCIA, SENHASMTP, SERVIDORSMTP, ULTNUMOP, USACREDCLIENTE, USUARIOSMTP, CODCONTACOMPRADEFAULT, CODCONTADEVENTRADADEFAULT, CODCONTADEVSAIDADEFAULT, CODCONTAFRETEPAGARDEFAULT, CODCONTAFRETERECEBERDEFAULT, CODCONTATRANSFDEPOSITODEFAULT, CODCONTAVENDADEFAULT, CODCONTAINVDEFAULT, CODCONTAREQDEFAULT, CONSIDERASABDIAUTIL, PERMITECLIDIF, PRECOALCOOL, PRECODIESEL, PRECOGASOLINA, UNESALDOCXBCO, USAAUTORIZACAOPAG, USACENTROCUSTO, USAPREC, USAROTEIRIZACAOENTREGA, USAROTEIRIZACAOVENDEDOR, UTILIZAEMBALAGEM, CODCONTAADIANTAMENTODEFAULT, BLOQATRASOCADCLIENTE, BLOQCHD1CADCLIENTE, BLOQCHD3CADCLIENTE, BLOQCHDVCADCLIENTE, BLOQUEIOCADCLIENTE, EXIBIRPRODSEMPRECIFICACAOFV, HORARIOBACKRED, MENSAGEMEMAILCOB, PORTASERVSN, PRECADASTROLIBERADOFV, SERVIDORSN, USAFOTOPRODUTOFV, UTILIZAEXPORTACAO, CODCONTADESCCONC, CODCONTADESCRECEB, CODCONTAJUROPAGO, CODCONTAJURORECEB, CODCONTARECEBER, CODTABELAPRECOPADRAO, BLOQDESBLOQCLIINITSISTEMA, ISCOBPLANOBRIG, DIASVALIDADEDAVSR, EDITAPRECOVENDADESCAUTOMATICO, ENVIAPEDIDOAUTFV, MENSAGEMEMAILCOB2, PERMITEALTPLANOCONTAS602, PORTASERVLOCAL, ISRAMOATVOBRIG, SERVIDORLOCAL, USAPONTOFIDELIDADE, UTILIZAEMPCADPESSOAVENDAFV, UTILPRECOMULTEMP, VLLIMITEPADRAONOVOCLIENTE, VLPONTOFIDCONC, VLPONTOFIDRESGATE, CODCOBRESGATE, PEDIDOSEMESTOQUEDAVFV, PEDIDOSEMESTOQUEPRONTAENTREGAFV, PEDIDOSEMESTOQUETELEMARKETINGFV, PERMITEALTDTENTREGAB2B, CODEMPPRECADASTROB2B, CODREGIAOPRECADASTROB2B, CODVENDPRECADASTROB2B, ENVIAPRODUTOSEMESTOQUEFV, ENVIAREMAILCONFPEDIDOB2B, GERARCODPRODUTOAUT, OPCAOENTREGAB2B, PERMITEALTDTLANCRECEITADESPESA, PRECADASTROLIBERADOB2B, TIPOENTREGAB2B, CODCONTATRANSCXBCODEFAULT, PEDIDOSEMESTOQUEB2B, EXIBIRPRODSEMPRECIFICACAO);
-- Table: LOGDESDCPAGAR
CREATE TABLE LOGDESDCPAGAR (ID, CODPARCELA, DTLANCAMENTO, DTLOG, DTVENCIMENTO, NUMNOTA, NUMPARCELA, TIPO, CODCOBRANCA, CODEMPRESA, CODFUNCDESD, CODPARCEIRO, CODCPAGAR);
-- Table: DETBCCREDITOPIS
CREATE TABLE DETBCCREDITOPIS (ID, CSTPIS, DESCCRED, DTFIM, DTINICIO, NATBCCRED, QUANTBCPIS, QUANTBCPISTOT, VLBCPIS, VLBCPISCUM, VLBCPISNC, VLBCPISTOT, VLBCTOTCSTALIQ, CODEMPRESA);
-- Table: CODTIPOCREDPISCOFINS
CREATE TABLE CODTIPOCREDPISCOFINS (CODIGO, CODGRUPO, DESCRICAO);
-- Table: SUBCONTA
CREATE TABLE SUBCONTA (CODIGO, DESCRICAO, CODGRUPO, CODCONTACONTABIL, DTULTALTERACAO);
-- Table: PARAMETROAPURACAOPISCOFINS
CREATE TABLE PARAMETROAPURACAOPISCOFINS (ID, CODCONTSOCIAL, CODCONTARECISENTA, CODRECEITAM205, CODRECEITAM605, NATRECISENTA_CST06, NATRECISENTA_CST07);
-- Table: LOGDESDCRECEBER
CREATE TABLE LOGDESDCRECEBER (ID, CODPARCELA, DTLANCAMENTO, DTLOG, DTVENCIMENTO, NUMNOTA, NUMPARCELA, TIPO, CODCOBRANCA, CODEMPRESA, CODFUNCDESD, CODPARCEIRO, CODCRECEBER, ROTINAORIGEM);
-- Table: DETCONTCOFINS
CREATE TABLE DETCONTCOFINS (ID, ALIQCOFINS, ALIQCOFINSQUANT, CODCONT, DTFIM, DTINICIO, QUANTBCCOFINS, VLAJUSACRES, VLAJUSREDUC, VLBCCONT, VLCONTAPUR, VLCONTDIFER, VLCONTDIFERANT, VLCONTPER, VLRECBRT, CODEMPRESA);
-- Table: COMISSAO
CREATE TABLE COMISSAO (CODIGO, DTBAIXA, DTCANCEL, DTESTORNO, DTLANC, ORIGEM, STATUS, VLCOMISSAO, CODFUNCBAIXA, CODFUNCCANCEL, CODFUNCESTORNO, CODFUNCLANC, CODEMPRESA, NUMNFEENTRADA, NUMNFESAIDA, NUMPEDIDO, CODVENDEDOR);
-- Table: SUBCONTACONTABIL
CREATE TABLE SUBCONTACONTABIL (CODCONTA, CNPJ, CODCONTAREFRFB, DTINCLUSAOALTER, NATUREZA, NIVEL, NOME, TIPO);
-- Table: PARAMETROCHECKOUT
CREATE TABLE PARAMETROCHECKOUT (CODIGO, QTDECIMAL, CODCLIENTEDEFAULT, CODNATOPDEFAULT, CODSUBCONTADEFAULT, AVISODIASVENCERTIFICADO, EXIBEDAVSEMRESERVAPDV, QTDIGBALANCAETIQ, UTILIZANATOPUSER, CODNATOP65PARA55, CODNATOPNFCE2, SATACSWHOUSE, SATCODATIVACAO, SATMARCA, ISCHECKOUTOFFLINE, DTULTATUALIZACAOBASICA, DTULTATUALIZACAO, PORTASERVIDOR, SERVIDOR);
-- Table: LOGDESDPCP
CREATE TABLE LOGDESDPCP (CODIGO, CODFORMULA_DEST, CODFORMULA_ORIG, CODFUNCDESD, DTDESD, NUMOP_DEST, NUMOP_ORIG);
-- Table: DETCONTCOFINSCODRECEITA
CREATE TABLE DETCONTCOFINSCODRECEITA (ID, CODREC, DTFIM, DTINICIO, NUMCAMPO, VLDEBITO, CODEMPRESA);
-- Table: COMISSAODESCDEPTO
CREATE TABLE COMISSAODESCDEPTO (ID, PERCOMISSAO, PERDESCFINAL, PERDESCINICIAL, CODDEPARTAMENTO);
-- Table: SUBCONTRATADOMDFE
CREATE TABLE SUBCONTRATADOMDFE (ID, NUMMDFE, CODTRANSPORTADORA);
-- Table: PARAMETROFV
CREATE TABLE PARAMETROFV (ABCCLIENTE, ABCPRODUTO, ISAGENDAMENTO, DTULTATUALIZACAO, DTULTENVIO, EMAIL, ISGPS, ISFORCAVENDAS, ISLOCALIZACAOUSUARIO, NOME, QTDEDIASATUALIZACAO, SENHA, USUARIO, VALORMINIMOVENDA, CODVEND, LATITUDE, LONGITUDE, ISROTEIRIZACAO, TIPOVENDAPADRAO, ENVIATODOSCLIENTESVEND, ISLOCALIZACAOATEND, PERMEDITARTIPOPEDIDO, PERMREALIZARPEDIDOFORALOCALIDADECLI, PERMREALIZARTROCA, ISVENDAMANIFESTO, ISFINANCEIRONEG, PERMACESSORELATORIOCOMISSAO, PERMLIBERACAOPEDIDO, USASUGESTAOVENDA, ISVENDTERCEIRIZADO, CODCLIVEND);
-- Table: LOGDUPLICARPEDIDO
CREATE TABLE LOGDUPLICARPEDIDO (CODIGO, CODIGOFUNCDUPLICACAO, DTDUPLICACAO, NUMPEDNOVO, NUMPEDORIG);
-- Table: DETCONTPIS
CREATE TABLE DETCONTPIS (ID, ALIQPIS, ALIQPISQUANT, CODCONT, DTFIM, DTINICIO, QUANTBCPIS, VLAJUSACRES, VLAJUSREDUC, VLBCCONT, VLCONTAPUR, VLCONTDIFER, VLCONTDIFERANT, VLCONTPER, VLRECBRT, CODEMPRESA);
-- Table: COMISSAODESCONTO
CREATE TABLE COMISSAODESCONTO (ID, PERCOMISSAO, PERDESCFINAL, PERDESCINICIAL);
-- Table: SUBCUSTO
CREATE TABLE SUBCUSTO (CODIGO, SUBNIVEL);
-- Table: PARAMETROINTEGRACAO
CREATE TABLE PARAMETROINTEGRACAO (CODIGO, CHAVEAPI, CODEMPRESA, TIPOINTEGRACAO);
-- Table: LOGEMISSAOBOLETO
CREATE TABLE LOGEMISSAOBOLETO (CODIGO, CODBANCO, CODBARRAS, CODEMPRESA, CODFUNC, DTREGISTRO, NOMEPC, NOSSONUMERO, NUMLANCAMENTO, OBSERVACAO, STATUS);
-- Table: DETCONTPISCODRECEITA
CREATE TABLE DETCONTPISCODRECEITA (ID, CODREC, DTFIM, DTINICIO, NUMCAMPO, VLDEBITO, CODEMPRESA);
-- Table: COMISSAOMOTORISTA
CREATE TABLE COMISSAOMOTORISTA (PERCOMISSAO, CODMOTORISTA);
-- Table: SUBMOD_ROTINA
CREATE TABLE SUBMOD_ROTINA (CODSUBMOD, CODROTINA);
-- Table: PARAMETROLICENCA
CREATE TABLE PARAMETROLICENCA (CODIGO, SNPARAM1, SNPARAM2, SNPARAM3, SNPARAM4, SNPARAM5, SNPARAM6, SNPARAM7, SNPARAM10, SNPARAM8, SNPARAM9, SNPARAM11, SNPARAM12, SNPARAM13, SNPARAM14, SNPARAM15, SNPARAM16);
-- Table: LOGFLEXIVEL
CREATE TABLE LOGFLEXIVEL (CODIGO, CODFUNC, CODPRODUTO, CODVENDEDOR, DATA, HISTORICO, NUMPED, ROTINA, TIPOMOV, VLINSERIDO, VLLIMITEANTERIOR, VLLIMITEATUAL, VLSALDOANTERIOR, VLSALDOATUAL);
-- Table: DETRECISENTACOFINS
CREATE TABLE DETRECISENTACOFINS (ID, CODCTA, DESCCOMPL, DTFIM, DTINICIO, NATREC, VLREC, CODEMPRESA);
-- Table: COMPROVANTECANHOTO
CREATE TABLE COMPROVANTECANHOTO (CODIGO, DTLANCAMENTO, IMAGEM, NUMLANCAMENTO, NUMSAIDA, TIPO);
-- Table: SUBMODULO
CREATE TABLE SUBMODULO (CODIGO, NOME);
-- Table: PARAMETROSEXECUCAOACESSO
CREATE TABLE PARAMETROSEXECUCAOACESSO (CODIGO, ALTERARSTATUSPRODUTO, ATUALIZARCAMPODTFECHACRECEBER, ATUALIZARSALDOADIANTAMENTO, VERIFICAROTINA1005, VERIFICAROTINA130, ATUALIZARTABELAIBTP, ATUALIZARCODGTIN, ATUALIZARNOMEROTINA106, ATUALIZAOBSNFSAIDA, ATUALIZARRNTRCPESSOA, ATUALIZARSCALEMETROCUBICOPRODUTO, ATUALIZARSTATUSCONFERENCIA, ATUALIZARSTATUSPESSOA, CARREGAINFOPAIS, CREATETRIGGERULTNUMNOTA, INSERIRPARAMETROSERVIDORSN, INSERIRTIPOVENDAPADRAOFV, INSERIRTOTMETROSCUBCARREGAMENTO, INSERTCFOPSEXPORTACAO, INSERTTIPOSPEDIDO, INSERTVENDEDORCOMPLEMENTOS, LIBERATPPEDIDODEFAULT, VERIFICAMUNEXT, VERIFICAROTINA1006, VERIFICAROTINA1007, VERIFICAROTINA131, VERIFICAROTINA132, VERIFICAROTINA133, VERIFICAROTINA206, VERIFICAROTINA207, VERIFICAROTINA208, ATUALIZARCAMPOOBSCTE, ATUALIZARCOMENTARIOPESSOA, ATUALIZARIPSERVIDORSN, ATUALIZARIPSERVIDORSN2, ATUALIZAOBSITEMMOVIMENTACAO, ATUALIZAOBSPEDIDO, ATUALIZAOBSERVACAONFENTRADA, ATUALIZARPERCBC_TRIBUTACAOICMS, ATUALIZARSCALEFTCONVPRODUTOFORN, ATUALIZARSTATUSCONFERENCIA205, ATUALIZARTABELAVENDEDOREMPRESAS1, ATUALIZARTAMCAMPOCODUNMOVIMENTACAO, ATUALIZARTAMCAMPOEMAILBOLETOPESSOA, ATUALIZARTAMCAMPONOTAPRODRURAL, ATUALIZARTIPOOPERACAOLOTE1401, CREATETRIGGERULTNUMCTE, INSERIRPRODUTOCOMPLEMENTO, INSERTBANDEIRASSITEF, INSERT_ENCIPI_NT2020_002, INSERT_MODBCST_NT2019_001, INSERTPESSOACOMPLEMENTOS, INSERTTABELASITAUEIRA, INSERTTBLAUXBUNGE, INSERTTIPOPEDTRANSF, INSERTURLSEFAZ, INSERTURLSEFAZ1, VERIFICAEMPRESACOMPLEMENTOS, VERIFICAESTCONTASPAGAR_MOVCXBCO, VERIFICAROTINA1008, VERIFICAROTINA1009, VERIFICAROTINA1204, VERIFICAROTINA1205, VERIFICAROTINA134, VERIFICAROTINA135, VERIFICAROTINA136, VERIFICAROTINA137, VERIFICAROTINA138, VERIFICAROTINA139, VERIFICAROTINA140, VERIFICAROTINA315, VERIFICAROTINA704, VERIFICAROTINA909, ALTERAR_TAMANHO_COLUNA_CBENEF, ALTERAR_VIEW_CONTROLE_BOLETO_BANCARIOS_V1, ALTERAR_VIEW_CONTROLE_BOLETO_BANCARIOS_V2, ATUALIZARCAMPO_STATUS_CONTROLECAIXAMOV, ATUALIZARDESONERACAOIMPOSTO101, ATUALIZAR_QTRENDIMENTO_PCPOP, ATUALIZAR_TABLE_LOGPRECOESTOQUE_V1, ATUALIZARTAMCAMPO_DADOSBANCARIO_PESSOA, ATUALIZARTAMCAMPOLOGALTSEGNIVELACESSO, ATUALIZARTAMCAMPO_MENSAGEMEMAILCOB2_PARAMETRO, ATUALIZARTAMCAMPO_OBSITEM_MOV, ATUALIZAR_TRIGGER_LOGPRECOESTOQUE_V1, CRIAR_INDEX_VIEW_CONTASARECEBERSITEF, CRIAR_SEQUENCE_RECIBO, CRIAR_VIEW_BLOQUEIO_DESBLOQUEIO_CLIENTE, CRIAR_VIEW_COMPROVANTECANHOTO, CRIAR_VIEW_CONTROLE_BOLETO_BANCARIOS, CRIAR_VIEW_PLATAFORMA_FINANCEIRA_CPAGAR, CRIAR_VIEW_PLATAFORMA_FINANCEIRA_CRECEBER, DROP_TABLE_CXBANCOPIXCD, DROPTABLE_CONTROLECAIXACLIENTE, INSERT_CODBCCREDPISCOFINS_CFOP_12, INSERT_MODBCST_7, INSERT_MODBC_4, PROCESSAR_AGENDAMENTOVISITACLIENTE, VERIFICAROTINA1206, VERIFICAROTINA1207, VERIFICAROTINA1208, VERIFICAROTINA316, VERIFICAROTINA620, VERIFICAROTINA626, VERIFICAROTINA705, VERIFICAROTINA807, VERIFICAROTINA910, VERIFICAROTINA911, VERIFICAROTINA912, VERIFICAROTINA913, INSERT_MODBCST_8, CREATETRIGGERULTNUMNFCE, DROPTABLELOGIMPORTNFCED1, VERIFICAROTINA808, ALTERAR_PARAMETRO_ESTOQUE_B2B, ALTERAR_PARAMETR_PRECIFICACAO_COMPOSICAO_CPV, ALTERAR_TAMANHO_CAMPO_CODFABRICA_PRODUTO, ALTERAR_TAMANHO_CAMPO_PIXTXID_CONTASARECEBER_COMPLEMENTOS, VERIFICAROTINA627, ALTERAR_VIEW_CONTROLE_BOLETO_BANCARIOS_V3);
-- Table: LOGIMPORTCUPOMFISCAL
CREATE TABLE LOGIMPORTCUPOMFISCAL (CODIGO, DTIMPORT, NUMSAIDACUPOM, NUMSAIDAGERADO);
-- Table: DETRECISENTAPIS
CREATE TABLE DETRECISENTAPIS (ID, CODCTA, DESCCOMPL, DTFIM, DTINICIO, NATREC, VLREC, CODEMPRESA);
-- Table: CONDUTORMDFE
CREATE TABLE CONDUTORMDFE (ID, CODPESSOA, NUMMDFE);
-- Table: SUPERVISOR
CREATE TABLE SUPERVISOR (CODSUPERVISOR, NOME, PERCOMISSAO, SENHA);
-- Table: PCPFORMULAAGREGADO
CREATE TABLE PCPFORMULAAGREGADO (CODIGO, PERCPERDA, QTDEPRODAGREGADO, TIPOOPAGREGADO, CODFORMULA, CODPRODUTO, PERVLAGREGADO, ativo, ORDEM);
-- Table: LOGIMPORTDAV
CREATE TABLE LOGIMPORTDAV (CODIGO, DTIMPORT, MODELO, NUMPEDIDODAV, NUMSAIDA, TIPODAV, TIPOVENDA);
-- Table: EMPRESA
CREATE TABLE EMPRESA (CODIGO, ABATEICMSCUSTO, ABATEPISCOFINSCUSTO, ALTERAPESO, BAIRRO, CELULAR, CEP, CNAE, CNPJ, CODCHAVEACESSOCTE, CODCHAVEACESSONFCE, CODCHAVEACESSONOTA, CODCSC, COMPLEMENTO, CRT, CSC, DESTVLTARIFACTE, DTAPURASPED, DTCADASTRO, DTULTALTERACAO, EMAIL, EMITENFCE, ENDERECO, ENTRADAESTBLOQ, EXIGEGRADETRIBUTACAO, FANTASIA, GERACREDDEVOLUCAO, IDLOJA, IE, IEST, IM, INSERECPFNANOTA, IPSERVIDORSITEF, LATITUDE, LONGITUDE, LUCRO, MARGEMCUSTO, MARGEMVENDA, MENSAGEMRODAPE, MODELOCTE, MODELONFCE, MODELONOTA, MODELONOTA2, NUMERO, PEDIDOTELEMARKETINGPENDENTE, PERCJUROAUTOMATICO, PERMITEALTERARPLANOCODCOB, RATEIASUBPRODPCP, RAZAOSOCIAL, RESPONSAVEL, RNTRC, SERIAL, SERIECTE, SERIEMDFE, SERIENFCE, SERIENOTA, SERIENOTA2, TELEFONE, TIPODOCMDFE, TIPOPEDIDO, TPPRECOVENDA, TIPOSEQUENCIALPADRAO, TIPOEMISSAONFCE, ULTNUMCTE, ULTNUMINVENTARIO, ULTNUMMDFE, ULTNUMNFCE, ULTNUMNOTA, ULTNUMNOTA2, ULTACRESCPRAZO, USADESCQUANTIDADE, USAMULTIPLOVENDEDOR, VLMAXQUEBRACAIXA, VENDEDORUSUARIOLOGADO, VLLIMTARIFAINTERNA, CODCFOPCTE, CODCIDADE, CODCLIENTEPADRAO, CODNATUREZACONSUMO, CODNATUREZAENTRADA, CODNATUREZASAIDA, CODNATUREZATRANSFDEPOSITO, CONSIDERARCOMISSAOCALCCPV, LAYOUTIMPRESSAOPADRAO, CONFERENCIAENTRADA, CONFERENCIASAIDAPORPEDIDO, NSUMDE, OBEDECERATEIOXML, OBEDECERGRADEICMS, CODNATUREZAINVENT);
-- Table: CONSOLIDACAOIPI
CREATE TABLE CONSOLIDACAOIPI (CFOP, CSTIPI, DTFIM, DTINICIO, VLBCIPI, VLCONTIPI, VLIPI, CODEMPRESA);
-- Table: TABELA
CREATE TABLE TABELA (CODTABELA, DESCRICAO, ATIVO);
-- Table: PCPFORMULAMATRIZ
CREATE TABLE PCPFORMULAMATRIZ (CODFORMULA, FORMULA, STATUS, TIPOOPMATRIZ, CODEMPRESA, CODPRODUTO, OBSERVACAO, QTRENDIMENTO);
-- Table: LOGIMPORTNFE
CREATE TABLE LOGIMPORTNFE (CODIGO, DTIMPORT, MODELO, MODELOREF, NUMNFE, NUMNFEREF, TIPOOPERACAO, TIPOOPERACAOREF);
-- Table: EMPRESA_COMPLEMENTOS
CREATE TABLE EMPRESA_COMPLEMENTOS (EXIBECEL, EXIBECOBRANCA, EXIBECODCLIENTE, EXIBEDADOSFATURAMENTO, EXIBEFANTASIA, EXIBEMOTORISTA, EXIBENUMCARGA, EXIBENUMPEDIDO, EXIBEVENDEDOR, IMPORTACPXML, MARGMINIMAPRECIFICACAO, RODAPEPADRAONOTA, CODEMPRESA, CODCIDADEDESTINOCARGA, CODCIDADEORIGEMCARGA, ACERTARNFCEBALCAO, DAVSEMRESERVAISORCAMENTO, ESTBLOCOK, EXIBECODCLIENTERAZSOCIAL, EXIBEENDENTREGA, EXIBEPUNITDESCDANFE, FRETEPORCONTA, LOTEIDENTIFICACAO, PERMITEBAIXARNAOACERTADOS, RECOLHIMENTOST, TIPOFRETEPADRAO, UTILIZACOMPLEMENTOMF, CODCLIDEFAULTCHECKOUT, LOCALIDADEENTRADAPADRAO, LOCALIDADESAIDAPADRAO, CODNATUREZAMANIFESTOVENDA, CODPAIS, ENTRADAESTDEVBLOQ, EXIBEICMSSTITENSDANFE, EXIBEVOLUMEITENSDANFE, GERACPAGARDEVOLUCAO, GLN, LAYOUTIMPRESSAOPADRAO308, MENSAGEMRODAPENFCE, ORDENACAOITEMDANFE, PERMITECONFSEMENTRADA, ULTNUMNOTAENTPY, UTILIZACONTROLECAIXA, CODCAIXABANCOPIX, CODNATOPB2B55, CODNATOPB2BD1, CODNATUREZAPREDEVOLUCAO, ULTNUMNOTAREMISIONPY);
-- Table: CONTA
CREATE TABLE CONTA (CODIGO, DESCRICAO);
-- Table: TABELA_COMPLEMENTOS
CREATE TABLE TABELA_COMPLEMENTOS (PERCOMISSAO, PERDESCONTO, PEROPERACIONAL, VLFRETETONELADA, CODTABELA);
-- Table: PCPOP
CREATE TABLE PCPOP (NUMOP, DTCANCELAMENTO, DTFIM, DTINICIO, DTLANCAMENTO, MOTIVOCANC, OBSFECHAMENTO, OBSERVACAO, QTPRODUZIDA, QTPRODUZIR, RESERVOUESTOQUE, STATUS, CODFORMULA, CODFUNCCANC, CODFUNCLANCAMENTO, CODEMPRESA, QTRENDIMENTO);
-- Table: LOGIMPRESSAONFCEMOBILE
CREATE TABLE LOGIMPRESSAONFCEMOBILE (CODIGO, CODFUNC, CODVENDEDOR, NUMSAIDA);
-- Table: ENQUADRAMENTOIPI
CREATE TABLE ENQUADRAMENTOIPI (CODIGO, DESCRICAO, GRUPOCST);
-- Table: CONTAMATERAEMPRESA
CREATE TABLE CONTAMATERAEMPRESA (ACCOUNTALIAS, ACCOUNTID, ACCOUNTSTATUS, CIDADE, CODIGOPAIS, CODIGOPOSTAL, ENDERECOIP, ESTADO, IDDISPOSITIVO, LATITUDE, LONGITUDE, NOMEPAIS, CODEMPRESA);
-- Table: TABELASCHECKOUT
CREATE TABLE TABELASCHECKOUT (CODTABELA);
-- Table: PCPOPAGREGADO
CREATE TABLE PCPOPAGREGADO (CODIGO, EXCESSOFALTAAGREGADO, OBSERVACAO, QUANTIDADE, TIPOOPAGREGADO, NUMOP, CODFORMULA, CODAGREGADO, CUSTOMEDIO);
-- Table: LOGIMPRESSOESPEDIDO
CREATE TABLE LOGIMPRESSOESPEDIDO (NUMPEDIDO, IMP303, IMPLISTCARGA1002);
-- Table: ENTRADA_ITEM_OCORRENCIA
CREATE TABLE ENTRADA_ITEM_OCORRENCIA (CODIGO, CODMOV, QUANTIDADE, CODOCORRENCIA);
-- Table: CONTASAPAGAR
CREATE TABLE CONTASAPAGAR (NUMLANCAMENTO, ISADIANTAMENTO, CODBANCO, CODBARRAS, ISDESDOBRADO, DESPREC, DESTREQ, DIASPRORROGADO, DTBAIXA, DTBORDERO, DTCHEQUE, DTDESD, DTLANCAMENTO, DTESTORNO, DTPAGAMENTO, DTPREDCHEQUE, DTPRORROGACAO, DTULTALTERACAO, DTVENCIMENTO, DTVENCORIGINAL, HISTORICO, ISCHBORDERO, MOTIVOCANCELAMENTO, NUMAGENCIA, NUMBORDERO, NUMCHEQUE, NUMCONTA, NUMNOTA, NUMPARCELA, OBSERVACAO, PERDESCONTO, PERJURO, ISPROVISAO, STATUS, TIPO, TOTPARCELAS, ISVALE, VALOR, VLDESCONTO, VLJURO, VLORIGINAL, VLPAGO, BANCO, CODCXBCO, CODCOBRANCA, CODFUNCBAIXA, CODFUNCBORDERO, CODFUNCCANCBORDERO, CODFUNCCANCCH, CODFUNCCHEQUE, CODFUNCDESD, CODFUNCESTORNO, CODFUNCLANCAMENTO, CODCONTA, NUMTRANSPORTE, CODCUSTO, CODEMPRESA, CODFORNECEDOR, CODMOEDA, NUMENTRADA, CODPLANOPGTO, CODVEICULO, DTDESPROVISAO, ENVIOLIBERACAO, STATUSLIBERACAO, REENVIOLIBERACAO);
-- Table: TBLAUXILIARBUNGE
CREATE TABLE TBLAUXILIARBUNGE (IDFORNECEDOR, EAN13, FORNECEDOR, PESO, PRODUTO, UNIDADECAIXA, UNIDADEDISPLAY);
-- Table: PEDAGIOMDFE
CREATE TABLE PEDAGIOMDFE (ID, CATEGORIAVEICULO, NUMCOMPROVANTE, VLPEDAGIO, CODFORNECEDOR, NUMMDFE, CODRESPONSAVEL);
-- Table: LOGINUTCTE
CREATE TABLE LOGINUTCTE (ID, CODSTATUS, DESCSTATUS, DTINUT, MODELO, MOTIVO, NUMFINAL, NUMINICIAL, NUMPROTOCOLO, SERIE, CODFUNCINUT, CODEMPRESA);
-- Table: ESTOQUE_LOTE_LAUDO
CREATE TABLE ESTOQUE_LOTE_LAUDO (CODIGO, DTANALISE, DTCANC, DTLANC, OBSERVACAO, CODESTLOTE, CODFUNCCANC, CODFUNCRESP);
-- Table: CONTASAPAGAR_MOVCXBCO
CREATE TABLE CONTASAPAGAR_MOVCXBCO (CODIGO, NUMLANCAMENTO, NUMTRANSACAO);
-- Table: TEMP
CREATE TABLE TEMP (ID, CODSESSAO, CODFILIALLOGADA, CODFUNCLOGADO, DTLOG);
-- Table: PERCURSOMDFE
CREATE TABLE PERCURSOMDFE (ID, NUMMDFE, UFPER);
-- Table: LOGINUTNFE
CREATE TABLE LOGINUTNFE (ID, CODSTATUS, DESCSTATUS, DTINUT, MODELO, MOTIVO, NUMFINAL, NUMINICIAL, NUMPROTOCOLO, SERIE, CODFUNCINUT, CODEMPRESA);
-- Table: ESTOQUE_LOTE_LAUDO_ATRIBUTOS
CREATE TABLE ESTOQUE_LOTE_LAUDO_ATRIBUTOS (CODIGO, NOME, OBSPADRAO, RESULTADO, VALORINDICADO, CODLAUDO);
-- Table: TIPOCALCULO
CREATE TABLE TIPOCALCULO (ID, DESCRICAO);
-- Table: PESSOA
CREATE TABLE PESSOA (CODIGO, ATIVO, BAIRRO, BAIRROCOBRANCA, BAIRROENTREGA, BLOQATRASO, BLOQCHD1, BLOQCHD3, BLOQCHDV, BLOQUEADO, CATEGORIA, CELULAR, CELCOBRANCA, CELENTREGA, CEP, CEPCOBRANCA, CEPENTREGA, CNPJ, COMENTARIO, COMISSAO, COMPLEMENTO, COMPCOBRANCA, COMPENTREGA, CONTATO, CRC, DADOSBANCARIO, DTADMISSAO, DTBLOQUEIO, DTCADASTRO, DTNASCIMENTO, DTULTALTERACAO, DTULTCOMPRA, DTVENCIMENTO, EMAIL, EMAILBOLETO, EMAILCOBRANCA, EMAILENTREGA, ENDERECO, ENDCOBRANCA, ENDENTREGA, FANTASIA, ISUF, IDESTRANGEIRO, IE, ISCLIENTE, ISCOLABORADOR, ISFORNECEDOR, ISMOTORISTA, ISTRANSPORTADORA, JUROS, MOTIVOBLOQUEIO, NOME, NUMAPOLICE, NUMAVERBACAO, NUMCNH, NUMREGISTRO, NUMERO, NUMCOBRANCA, NUMENTREGA, PRAZOENTREGA, RNTRC, SENHA, STATUSALTERACAO, STATUSFV, TELEFONE, TELCOBRANCA, TELENTREGA, TIPOMOTORISTA, TIPOPESSOA, USUARIO, VLCREDDISPONIVEL, VLCREDUTILIZADO, VLLIMITECRED, CODCIDADE, CODCIDADECOBRANCA, CODCIDADEENTREGA, CODCOBRANCA, CODRAMOATIVIDADE, CODEMPRESA, CODNIVELACESSO, CODPLANOPGTO, CODREGIAO, CODSEGNIVELACESSO, CODSETOR, CODTABELA, TIPOCALCULO, CODVENDEDOR, CODVENDEDOR2, CODVENDEDOR3, CODVENDEDOR4, COBRANCAPERSONALIZADA, LATITUDE, LONGITUDE);
-- Table: LOGLOTESINFPORNFCE
CREATE TABLE LOGLOTESINFPORNFCE (NUMSAIDA, CODFUNC, DATA);
-- Table: ESTOQUELOTE
CREATE TABLE ESTOQUELOTE (CODIGO, CODEMPRESA, CODPRODUTO, DTPROD, DTVENC, NUMLOTE, QTBLOQUEADA, QTDISPONIVEL, QTESTOQUE, QTRESERVADA, VALIDADE);
-- Table: CONTASARECEBER
CREATE TABLE CONTASARECEBER (NUMLANCAMENTO, ALINEA, CODBANCO, CODBARRAS, ISCXFECHADO, ISDESDOBRADO, DESPREC, DESTREQ, DIASPRORROGADO, DTBAIXA, DTBOLETO, DTCOBRANCA, DTDESD, DTLANCAMENTO, DTESTORNO, DTFECHA, DTPAGAMENTO, DTPREVPAGAMENTO, DTPRORROGACAO, DTREMESSA, DTRETORNO, DTULTALTERACAO, DTVENCIMENTO, DTVENCORIGINAL, GEROUREMESSA, HISTORICO, NOSSONUMERO, NSUHOST, NUMAGENCIA, NUMBORDERO, NUMCHEQUE, NUMCONTA, NUMDOCUMENTO, NUMNOTA, NUMPARCELA, NUMREMESSA, NUMRETORNO, OBSCOBRANCA, OBSERVACAO, CODOCORRENCIA, PERDESCONTO, PERJURO, PROTOCOLO, SEUNUMERO, STATUS, STATUSMOVIMENTO, STATUSTEF, TIPO, TIPOACOMPCOBRANCA, TOTPARCELAS, VALOR, VLDESCONTO, VLJURO, VLORIGINAL, VLPAGO, BANCO, CODCXBCO, CODCXPDV, NUMCARGA, CODCLIENTE, CODCOBRANCA, CODFUNCBAIXA, CODFUNCDESD, CODFUNCESTORNO, CODFUNCFECHA, CODFUNCLANCAMENTO, CODCONTA, NUMTRANSPORTE, CODCUSTO, CODEMPRESA, CODMOEDA, NUMENTRADADEV, NUMSAIDA, CODPLANOPGTO, PESSOAPROTOCOLO, CODVEICULO, NUMACERTO, CODOPERADOR);
-- Table: TIPOITEM
CREATE TABLE TIPOITEM (ID, CODIGO, DESCRICAO, DATAINCLUSAO, ATIVO);
-- Table: PESSOA_COMPLEMENTOS
CREATE TABLE PESSOA_COMPLEMENTOS (ISADMCARTAOPDV, ISCONTRIBUINTE, REFENTREGA, CODPESSOA, CODFUNCALTERACAO, CODREDE, DESONERAICMS, DESONERAIPI, DESONERAPISCOFINS, FRETEPORCONTA, GLN, GLNCOBRANCA, GLNENTREGA, MODELONOTAPADRAO, PLANOPGTOPERSONALIZADO, QTMAXCOMODATO, TIPOFRETE, CODCONTACONTABIL, CODSUBCONTA, CODSUBCUSTO, CODNATOPERACAOPADRAO, CODTRANSPORTADORA);
-- Table: LOGPEDIDOFV
CREATE TABLE LOGPEDIDOFV (ID, NUMPEDIDOFV, VERSAOFV, VERSAOWEBSERVICE, NUMPEDIDOERP, DTENVIO, UTILIZOUTROCA);
-- Table: FABRICANTE
CREATE TABLE FABRICANTE (CODIGO, FABRICANTE, DTULTALTERACAO);
-- Table: CONTASARECEBER_COMPLEMENTOS
CREATE TABLE CONTASARECEBER_COMPLEMENTOS (CODSOLICAPICOBRANCA, NUMRECIBO, PIXCOPIAECOLA, PIXTXID, STATUSBANCO, NUMLANCAMENTO);
-- Table: TIPOPEDIDO
CREATE TABLE TIPOPEDIDO (ID, DESCRICAO);
-- Table: VW_BLOQUEIO_DESBLOQUEIO_CLIENTE
CREATE TABLE VW_BLOQUEIO_DESBLOQUEIO_CLIENTE (PESSOA_CODCLIENTE, CR_BLOQUEAR);
-- Table: ACAOJUDICPISCOFINS
CREATE TABLE ACAOJUDICPISCOFINS (ID, DESCDECJUD, DTSENTJUD, IDSECJUD, IDVARA, INDNATACAO, NUMPROC, CODEMPRESA);
-- Table: PESSOA_EXPORTACAO
CREATE TABLE PESSOA_EXPORTACAO (LOCDESPACHO, LOCEXPORTA, CODCLIENTE, CODPAIS, UFSAIDAPAIS);
-- Table: LOGPEDIDOINTEGRACAO
CREATE TABLE LOGPEDIDOINTEGRACAO (CODIGO, CODFUNCLANC, DTLANC, NUMPEDIDOREF, TIPOINTEGRACAO, VERSAOERP, NUMPEDIDOERP);
-- Table: FECHAMENTOCAIXAPDV
CREATE TABLE FECHAMENTOCAIXAPDV (ID, DTFECHA1, DTFECHA2, STATUS, VALORDIGITADO, NUMCAIXAPDV, CODCOBRANCA, CODEMPRESA, CODOPERADOR, VALORTOTAL, OBSERVACAO, VALORDIFERENCA, VALORSANGRIA, VALORSUPRIMENTO, ENVIOCHECKOUT);
-- Table: CONTASARECEBER_MOVCXBCO
CREATE TABLE CONTASARECEBER_MOVCXBCO (CODIGO, ISORIGINAL, NUMLANCAMENTO, NUMTRANSACAO);
-- Table: VW_COMPROVANTECANHOTO
CREATE TABLE VW_COMPROVANTECANHOTO (CPC_CODIGO, CPC_DTLANCAMENTO, CPC_NUMLANCAMENTO, CPC_NUMSAIDA, CPC_TIPO);
-- Table: TIPOUTILCREDFISICMS
CREATE TABLE TIPOUTILCREDFISICMS (CODIGO, DESCRICAO, DTFIM, DTINICIO);
-- Table: VW_CONTASARECEBER_SITEF
CREATE TABLE VW_CONTASARECEBER_SITEF (CRECEBER_NUMLANCAMENTO, CRECEBER_CODCLIENTE, CRECEBER_CODCOBRANCA, CRECEBER_NSUHOST, CRECEBER_VALOR, CRECEBER_VLPAGO, CRECEBER_VLORIGINAL, CRECEBER_STATUS, CRECEBER_NUMNOTA, CUPOMSITEF_VALOR, CUPOMSITEF_CODAUTORIZA, CUPOMSITEF_CODBANDEIRA, CUPOMSITEF_NSUSITEF, NF_STATUS, COB_TIPOCOBRANCA);
-- Table: ACERTOCAIXA
CREATE TABLE ACERTOCAIXA (ID, DTFECHA1, DTFECHA2, NUMCAIXA, VLTOTAL, CODCXBCO, NUMCARGA, CODFUNCFECHA, CODEMPRESA, CODMOTORISTA, CODVEICULO);
-- Table: PESSOA2
CREATE TABLE PESSOA2 (CODIGO, NOME, IE, UF, CODCIDADE, ATIVO, BAIRRO, BAIRROCOBRANCA, BAIRROENTREGA, BLOQATRASO, BLOQCHD1, BLOQCHD3, BLOQCHDV, BLOQUEADO, CATEGORIA, CELULAR, CELCOBRANCA, CELENTREGA, CEP, CEPCOBRANCA, CEPENTREGA, CNPJ, COMENTARIO, COMISSAO, COMPLEMENTO, COMPCOBRANCA, COMPENTREGA, CONTATO, CRC, DADOSBANCARIO, DTADMISSAO, DTBLOQUEIO, DTCADASTRO, DTNASCIMENTO, DTULTALTERACAO, DTULTCOMPRA, DTVENCIMENTO, EMAIL, EMAILBOLETO, EMAILCOBRANCA, EMAILENTREGA, ENDERECO, ENDCOBRANCA, ENDENTREGA, FANTASIA, ISUF, IDESTRANGEIRO, ISCLIENTE, ISCOLABORADOR, ISFORNECEDOR, ISMOTORISTA, ISTRANSPORTADORA, JUROS, MOTIVOBLOQUEIO, NUMAPOLICE, NUMAVERBACAO, NUMCNH, NUMREGISTRO, NUMERO, NUMCOBRANCA, NUMENTREGA, PRAZOENTREGA, RNTRC, SENHA, STATUSALTERACAO, STATUSFV, TELEFONE, TELCOBRANCA, TELENTREGA, TIPOMOTORISTA, TIPOPESSOA, USUARIO, VLCREDDISPONIVEL, VLCREDUTILIZADO, VLLIMITECRED, TempCODCIDADE, CODCIDADECOBRANCA, CODCIDADEENTREGA, CODCOBRANCA, CODRAMOATIVIDADE, CODEMPRESA, CODNIVELACESSO, CODPLANOPGTO, CODREGIAO, CODSEGNIVELACESSO, CODSETOR, CODTABELA, TIPOCALCULO, CODVENDEDOR, CODVENDEDOR2, CODVENDEDOR3, CODVENDEDOR4, COBRANCAPERSONALIZADA, LATITUDE, LONGITUDE, PESS_ID);
-- Table: LOGPIXOPERACOES
CREATE TABLE LOGPIXOPERACOES (CODIGO, DATA, NUMPEDIDO, COPIAECOLA, PIXREVISAO, PIXTXID, ROTINA, APIORIGEM, OPERACAO);
-- Table: FILIALCXBCO
CREATE TABLE FILIALCXBCO (CODCXBCO, CODEMPRESA);
-- Table: PESSOAUSUARIOB2B
CREATE TABLE PESSOAUSUARIOB2B (ATIVO, SENHA, USUARIO, CODPESSOA);
-- Table: CONTCREDCOFINS
CREATE TABLE CONTCREDCOFINS (ID, CNPJSUC, CODCRED, ORIGCRED, PERAPUCRED, PERDESCCRED, SDCREDDISPEFD, SLDCREDFIM, VLCREDAPU, VLCREDDCOMPEFD, VLCREDDCOMPPAANT, VLCREDDESCEFD, VLCREDDESCPAANT, VLCREDEXTAPU, VLCREDOUT, VLCREDPEREFD, VLCREDPERPAANT, VLCREDTRANS, VLTOTCREDAPU, CODEMPRESA);
-- Table: TRIBUTACAOICMS
CREATE TABLE TRIBUTACAOICMS (CODIGO, PERCFCPDEST, PERCINTERESTADUAL, PERCINTERNADEST, PERCPARTILHA, OBSERVACAO, PERCENTUALBASECALCULO, PERCENTUALBASECALCULOST, PERCENTUALCREDITOSIMPLES, PERCENTUALDIFERIMENTO, PERCENTUALICMS, PERCENTUALICMSST, PERCENTUALINTERNO, PERCENTUALMVA, PERCPARTILHADEST, PERCPARTILHAREMET, VALORPAUTA, CFOP, CSOSN, CST, GRUPOICMS, MODALIDADEBASECALCULO, MODALIDADEBASECALCULOST, NATUREZAOPERACAO, ORIGEM, TIPOCALCULO, UF, DTULTALT, CODBENEF, PERCFCPST, PERCENTUALBASECALCULOBASEST, PERIRRF, PERRETCOFINS, PERCSLL, PERRETPIS, CODFUNCALT);
-- Table: VW_FV_PRECO_ESTOQUE
CREATE TABLE VW_FV_PRECO_ESTOQUE (PREC_CODEMPRESA, PROD_CODIGO, PROD_CODPRODPRINC, PROD_NOME, PROD_UNIDADE, PROD_ATIVO, PREC_CUSTOMANUAL, PREC_CUSTOMEDIO, PREC_CUSTOULTENTRADA, PREC_QTBLOQUEADA, PREC_QTDISPONIVEL, PREC_QTESTOQUE, PREC_QTRESERVADA, PREC_QTPENDENTE, QTESTOQUEMINIMO, PREC_CODGRUPOIPI, IPI_DESC, PREC_CODGRUPOICMS, ICMS_DESC, CODGRUPOPISCOFINS, PISCONFINS_DESC, PREC_USAESTLOTE, PREC_DTULTALTERACAO);
-- Table: ACOMPANHAMENTOENTREGAVEICULO
CREATE TABLE ACOMPANHAMENTOENTREGAVEICULO (CODIGO, DTCHECKIN, DTCHECKOUT, DTENTREGA, LATITUDE, LONGITUDE, OBSERVACAO, PLACA, NUMCARGA, NUMNFSAIDA);
-- Table: LOGPRECIFICACAO
CREATE TABLE LOGPRECIFICACAO (ID, DTALTERACAO, PRECOANTERIOR, PRECOALT, CODFUNCALT, CODEMPRESA, CODPRODUTO, CODREGIAO, CODTABELA);
-- Table: GENEROITEM
CREATE TABLE GENEROITEM (ID, CODIGO, DESCRICAO, DATAINCLUSAO, ATIVO);
-- Table: VW_FV_RELATORIO_VENDA
CREATE TABLE VW_FV_RELATORIO_VENDA (EMP_COD, EMP_RAZAO, EMP_FANTASIA, EMP_CNPJ, EMP_TELEFONE, CLI_CODIGO, CLI_CLIENTE, CLI_FANTASIA, CLI_CNPJ, CLI_IE, CLI_END, CLI_NUMERO, CLI_CEP, CLI_CIDADE, CLI_BAIRRO, CLI_TELEFONE, CLI_COMPLEMENTO, CLI_UF, VLTOTITENS, PERDESCVENDA, VLDESCVENDA, VLTOTIPI, VLTOTICMSST, VLFRETE, VLTOTFCPST, VLTOTNOTA, QTITENS, TIPOFRETE, COB_DESCRICAO, PLANO_PAGAMENTO, TOTPESOBRUTO, TOTPESOLIQUIDO, VEND_NOME, NUMPED, NUMNOTA, DTEMISSAO, DTPREVENTREGA, STATUS, TIPOVENDA, ISFATURADO, OBSPEDIDO, OBSERVACAO, CODVENDEDOR, CODEMPRESA, VLTOTRESTANTE, VLTOTENTREGUE, APPORIGEM, CARGA_STATUS, CARGA_ISENTREGUE, CARGA_ISANDAMENTO, CARGA_DTFECHA);
-- Table: CONTCREDPIS
CREATE TABLE CONTCREDPIS (ID, CNPJSUC, CODCRED, ORIGCRED, PERAPUCRED, PERDESCCRED, SDCREDDISPEFD, SLDCREDFIM, VLCREDAPU, VLCREDDCOMPEFD, VLCREDDCOMPPAANT, VLCREDDESCEFD, VLCREDDESCPAANT, VLCREDEXTAPU, VLCREDOUT, VLCREDPEREFD, VLCREDPERPAANT, VLCREDTRANS, VLTOTCREDAPU, CODEMPRESA);
-- Table: TRIBUTACAOIPI
CREATE TABLE TRIBUTACAOIPI (CODIGO, PERCENTUALBASECALCULO, PERCENTUALIPI, VALORUNIDADEIPI, CSTIPI, GRUPOIPI, NATUREZAOPERACAO, DTULTALTERACAO);
-- Table: VW_PLATAFORMA_FINANCEIRA_CPAGAR
CREATE TABLE VW_PLATAFORMA_FINANCEIRA_CPAGAR (CP_NUMLANCAMENTO, CP_ISADIANTAMENTO, CP_CODBANCO, CP_CODBARRAS, CP_ISDESDOBRADO, CP_DESPREC, CP_DESTREQ, CP_DIASPRORROGADO, CP_DTBAIXA, CP_DTBORDERO, CP_DTCHEQUE, CP_DTDESD, CP_DTLANCAMENTO, CP_DTESTORNO, CP_DTPAGAMENTO, CP_DTPREDCHEQUE, CP_DTPRORROGACAO, CP_DTULTALTERACAO, CP_DTVENCIMENTO, CP_DTVENCORIGINAL, CP_HISTORICO, CP_ISCHBORDERO, CP_MOTIVOCANCELAMENTO, CP_NUMAGENCIA, CP_NUMBORDERO, CP_NUMCHEQUE, CP_NUMCONTA, CP_NUMNOTA, CP_NUMPARCELA, CP_OBSERVACAO, CP_PERDESCONTO, CP_PERJURO, CP_ISPROVISAO, CP_STATUS, CP_TIPO, CP_TOTPARCELAS, CP_ISVALE, CP_VALOR, CP_VLDESCONTO, CP_VLJURO, CP_VLORIGINAL, CP_VLPAGO, CP_BANCO, CP_CODCXBCO, CXBCO_NOMECXBANCO, CP_CODFUNCBAIXA, PES_NOMEFUNCBAIXA, CP_CODFUNCDESD, PES_NOMEFUNCDESD, CP_CODFUNCLANCAMENTO, PES_NOMEFUNCLANCAMENTO, CP_CODCONTA, SCONTA_NOMESUBCONTA, CP_CODCUSTO, SCUSTO_NOMESUBCUSTO, CP_CODEMPRESA, EMP_NOMEEMPRESA, CP_CODFORNECEDOR, PES_NOMEFORNECEDOR, CP_CODMOEDA, CP_NUMENTRADA, CP_CODPLANOPGTO, CP_CODVEICULO, VEI_NOMEVEICULO, CP_DTDESPROVISAO, CP_ENVIOLIBERACAO, CP_STATUSLIBERACAO, CP_REENVIOLIBERACAO, CP_CODCOBRANCA);
-- Table: ADIANTAMENTO
CREATE TABLE ADIANTAMENTO (NUMLANCAMENTO, ISBAIXADO, DTBAIXA, DTCANCELAMENTO, DTESTORNO, DTLANCAMENTO, DTVENCIMENTO, HISTORICO, NUMNOTA, TIPO, VALOR, CODCXBCO, CODFUNCBAIXA, CODFUNCESTORNOS, CODFUNCLANC, CODEMPRESA, CODMOEDA, CODPARCEIRO, CODTITULO, CODVEICULO, VLSALDO);
-- Table: PLANOCLI
CREATE TABLE PLANOCLI (CODCLIENTE, CODPLANOPGTO);
-- Table: LOGREGISTROATIVSEFAZ
CREATE TABLE LOGREGISTROATIVSEFAZ (CODIGO, CODEMPRESA, DTREGISTRO, ROTINA, TIPOREGISTRO, CHAVEACESSO, CODFUNC, NOMEPC, NUMSAIDA, OBSERVACAO, ISTRANSMISSAO);
-- Table: GESTAOINFO
CREATE TABLE GESTAOINFO (ID, VERSAOAPLI);
-- Table: VW_PLATAFORMA_FINANCEIRA_CRECEBER
CREATE TABLE VW_PLATAFORMA_FINANCEIRA_CRECEBER (CR_NUMLANCAMENTO, CR_ISCXFECHADO, CR_ISDESDOBRADO, CR_DIASPRORROGADO, CR_DTBAIXA, CR_DTBOLETO, CR_DTCOBRANCA, CR_DTDESD, CR_DTLANCAMENTO, CR_DTESTORNO, CR_DTFECHA, CR_DTPAGAMENTO, CR_DTPREVPAGAMENTO, CR_DTPRORROGACAO, CR_DTREMESSA, CR_DTRETORNO, CR_DTULTALTERACAO, CR_DTVENCIMENTO, CR_DTVENCORIGINAL, CR_GEROUREMESSA, CR_HISTORICO, CR_NOSSONUMERO, CR_NUMAGENCIA, CR_NUMBORDERO, CR_NUMCHEQUE, CR_NUMCONTA, CR_NUMDOCUMENTO, CR_NUMNOTA, CR_NUMPARCELA, CR_NUMREMESSA, CR_NUMRETORNO, CR_OBSCOBRANCA, CR_CODOCORRENCIA, CR_PERDESCONTO, CR_PERJURO, CR_PROTOCOLO, CR_SEUNUMERO, CR_STATUS, CR_STATUSMOVIMENTO, CR_TIPO, CR_TIPOACOMPCOBRANCA, CR_TOTPARCELAS, CR_VALOR, CR_VLDESCONTO, CR_VLJURO, CR_VLORIGINAL, CR_VLPAGO, CR_BANCO, CR_CODCXBCO, CXBANCO_NOME, CR_CODCXPDV, CXPDV_NUMCAIXA, CR_NUMCARGA, CR_CODCLIENTE, PESSOA_NOME, CR_CODCOBRANCA, COBRANCA_DESCRICAO, CR_CODFUNCBAIXA, FUNCBAIXA_NOME, CR_CODFUNCDESD, FUNCDESD_NOME, CR_CODFUNCESTORNO, FUNCESTORNO_NOME, CR_CODFUNCFECHA, FUNCFECHA_NOME, CR_CODFUNCLANCAMENTO, FUNCLANC_NOME, CR_CODCONTA, SUBCONTA_DESCRICAO, CR_CODCUSTO, SUBCUSTO_NIVEL, CR_CODEMPRESA, CR_CODMOEDA, CR_NUMENTRADADEV, CR_NUMSAIDA, CR_CODPLANOPGTO, PLANOPGTO_PLANO, CR_CODVEICULO, VEICULO_PLACA, VEICULO_DESCRICAO, CR_NUMACARTO, CR_CODOPERADOR);
-- Table: PLANOPGTO
CREATE TABLE PLANOPGTO (CODIGO, NUMPARCELAS, PLANO, PRAZO1, PRAZO10, PRAZO11, PRAZO12, PRAZO13, PRAZO14, PRAZO15, PRAZO16, PRAZO17, PRAZO18, PRAZO19, PRAZO2, PRAZO20, PRAZO3, PRAZO4, PRAZO5, PRAZO6, PRAZO7, PRAZO8, PRAZO9, PRAZOMEDIO, STATUSFV, TXFINANCEIRA, TXFINANPGTO);
-- Table: CONTRIBUICAOCOFINS
CREATE TABLE CONTRIBUICAOCOFINS (DTFIM, DTINICIO, VLCONTCUMREC, VLCONTNCREC, VLOUTDEDCUM, VLOUTDEDNC, VLRETCUM, VLRETNC, VLTOTCONTCUMPER, VLTOTCONTNCDEV, VLTOTCONTNCPER, VLTOTCONTREC, VLTOTCREDDESC, VLTOTCREDDESCANT, CODEMPRESA);
-- Table: TRIBUTACAOPISCOFINS
CREATE TABLE TRIBUTACAOPISCOFINS (CODIGO, PERBASECALCULOCOFINS, PERBASECALCULOPIS, PERBASECALCULOSTCOFINS, PERBASECALCULOSTPIS, PERCOFINS, PERPIS, PERSTCOFINS, PERSTPIS, CSTCOFINS, CSTPIS, GRUPOPISCOFINS, NATUREZAOPERACAO, DTULTALTERACAO);
-- Table: ADIANTAMENTO_CONTASAPAGAR
CREATE TABLE ADIANTAMENTO_CONTASAPAGAR (NUMADIANTAMENTO, NUMCPAGAR);
-- Table: LOGREQTRANSFERENCIA
CREATE TABLE LOGREQTRANSFERENCIA (CODIGO, CODMOV, DESTINO, DTLOG, NUMCPAGAR, NUMCRECEBER, NUMNOTA, TIPOMOV);
-- Table: GRUPOALTERACAOCCECTE
CREATE TABLE GRUPOALTERACAOCCECTE (ID, DESCRICAO, GRUPO);
-- Table: PLANOPGTO_COMPLEMENTOS
CREATE TABLE PLANOPGTO_COMPLEMENTOS (DTULTALTERACAO, CODPLANOPGTO, CODFUNCULTALT);
-- Table: CONTRIBUICAOPIS
CREATE TABLE CONTRIBUICAOPIS (DTFIM, DTINICIO, VLCONTCUMREC, VLCONTNCREC, VLOUTDEDCUM, VLOUTDEDNC, VLRETCUM, VLRETNC, VLTOTCONTCUMPER, VLTOTCONTNCDEV, VLTOTCONTNCPER, VLTOTCONTREC, VLTOTCREDDESC, VLTOTCREDDESCANT, CODEMPRESA);
-- Table: UF
CREATE TABLE UF (UF, NOME, SIGLA);
-- Table: ADIANTAMENTO_HISTMOV
CREATE TABLE ADIANTAMENTO_HISTMOV (CODIGO, DTBAIXA, DTESTORNO, HISTORICO, VALOR, NUMADIANTA, CODCXBCO, CODEMPRESA, CODFUNCLANC, CODMOEDA);
-- Table: LOGSUGESTAOVENDA
CREATE TABLE LOGSUGESTAOVENDA (CODIGO, CODPRODUTO, CODVENDEDOR, DTSUGESTAO, NUMPEDIDO, QTESTCLIENTE, QTINTVISITAS, QTSUGERIDA);
-- Table: GRUPOICMS
CREATE TABLE GRUPOICMS (ID, DESCRICAO, DTULTALTERACAO);
-- Table: CONTASARECEBER2
CREATE TABLE CONTASARECEBER2 (NUMNOTA, DTVENCIMENTO, DTLANCAMENTO, CNPJ, VALOR, NUMLANCAMENTO, ALINEA, CODBANCO, CODBARRAS, ISCXFECHADO, ISDESDOBRADO, DESPREC, DESTREQ, DIASPRORROGADO, DTBAIXA, DTBOLETO, DTCOBRANCA, DTDESD, DTESTORNO, DTFECHA, DTPAGAMENTO, DTPREVPAGAMENTO, DTPRORROGACAO, DTREMESSA, DTRETORNO, DTULTALTERACAO, DTVENCORIGINAL, GEROUREMESSA, HISTORICO, NOSSONUMERO, NSUHOST, NUMAGENCIA, NUMBORDERO, NUMCHEQUE, NUMCONTA, NUMDOCUMENTO, NUMPARCELA, NUMREMESSA, NUMRETORNO, OBSCOBRANCA, OBSERVACAO, CODOCORRENCIA, PERDESCONTO, PERJURO, PROTOCOLO, SEUNUMERO, STATUS, STATUSMOVIMENTO, STATUSTEF, TIPO, TIPOACOMPCOBRANCA, TOTPARCELAS, VLDESCONTO, VLJURO, VLORIGINAL, VLPAGO, BANCO, CODCXBCO, CODCXPDV, NUMCARGA, CODCLIENTE, CODCOBRANCA, CODFUNCBAIXA, CODFUNCDESD, CODFUNCESTORNO, CODFUNCFECHA, CODFUNCLANCAMENTO, CODCONTA, NUMTRANSPORTE, CODCUSTO, CODEMPRESA, CODMOEDA, NUMENTRADADEV, NUMSAIDA, CODPLANOPGTO, PESSOAPROTOCOLO, CODVEICULO, NUMACERTO, CODOPERADOR);
-- Table: PONTOSFIDELIDADE
CREATE TABLE PONTOSFIDELIDADE (CODIGO, CODCLIENTE, CODFUNCLANC, DTLANC, NUMENTRADA, NUMSAIDA, QTPONTOS, STATUS, TIPOMOV, TIPOOPERACAO, VLPONTOS);
-- Table: CONTROLECAIXA
CREATE TABLE CONTROLECAIXA (CODIGO, CODEMPRESA, CODPRODUTO, QTCLIENTE, QTEMPRESA, QTTRANSITO);
-- Table: UNIDADE
CREATE TABLE UNIDADE (UNIDADE, DESCRICAO);
-- Table: ADICAODECIMPORTACAO
CREATE TABLE ADICAODECIMPORTACAO (ID, NADICAO, NDRAW, NSEQADIC, VLDESCDI, CFABRICANTE, IDDI);
-- Table: LOGTRANSPEDCARGA
CREATE TABLE LOGTRANSPEDCARGA (CODIGO, CODFUNCALT, DTTRANS, NUMCARGADESTINO, NUMCARGAORIGEM, NUMPEDIDO);
-- Table: GRUPOIPI
CREATE TABLE GRUPOIPI (ID, DESCRICAO, CODIGOENQUADRAMENTO, DTULTALTERACAO);
-- Table: PRECOTABELA2
CREATE TABLE PRECOTABELA2 (CODIGO, NOME, CATEGORIA, CUSTOMEDIO, PERICMSCPV, PERPISCOFINSCPV, PERPISCOFINSCPV1, IR CS (OPERACIONAL), Custo OP (OPERACIONAL), PERCOMISSAO, PERMARGEMLUCRO, TX CARTÃO (OPERACIONAL), Frete s/ Venda (OPERACIONAL), PRECOCONSUMIDOR, PRECOMINIMO, CODTABELA);
-- Table: POSNFCE
CREATE TABLE POSNFCE (ID, CODAUTORIZACAO, STATUS, CODADMCARTAO, CODCOBRANCA, NUMLANCAMENTO);
-- Table: CONTROLECAIXA_CARGA
CREATE TABLE CONTROLECAIXA_CARGA (HISTORICO, STATUS, NUMCARGA);
-- Table: URLSEFAZ
CREATE TABLE URLSEFAZ (CODIGO, QRCODE, TIPOAMBIENTE, URL, UF);
-- Table: CONTASAPAGAR2
CREATE TABLE CONTASAPAGAR2 (NUMNOTA, DTLANCAMENTO, DTVENCIMENTO, HISTORICO, VLORIGINAL, VLPAGO, VALOR2, ISADIANTAMENTO, BANCO, CODCXBCO, CODCOBRANCA, CODBANCO, CODBARRAS, CODFUNCBAIXA, CODFUNCBORDERO, CODFUNCCANCBORDERO, CODFUNCCANCCH, CODFUNCCHEQUE, CODFUNCDESD, CODFUNCESTORNO, CODFUNCLANCAMENTO, CODCONTA, NUMTRANSPORTE, CODCUSTO, ISDESDOBRADO, DESPREC, DESTREQ, DIASPRORROGADO, DTBAIXA, DTBORDERO, DTCHEQUE, DTDESD, DTDESPROVISAO, DTESTORNO, DTPAGAMENTO, DTPREDCHEQUE, DTPRORROGACAO, DTULTALTERACAO, DTVENCORIGINAL, ENVIOLIBERACAO, CODEMPRESA, CODFORNECEDOR, ISCHBORDERO, CODMOEDA, MOTIVOCANCELAMENTO, NUMAGENCIA, NUMBORDERO, NUMCHEQUE, NUMCONTA, NUMENTRADA, NUMPARCELA, OBSERVACAO, PERDESCONTO, PERJURO, CODPLANOPGTO, ISPROVISAO, REENVIOLIBERACAO, STATUS, STATUSLIBERACAO, TIPO, TOTPARCELAS, ISVALE, VALOR, CODVEICULO, VLDESCONTO, VLJURO, NUMLANCAMENTO);
-- Table: AGENDAMENTOVISITACLIENTE
CREATE TABLE AGENDAMENTOVISITACLIENTE (DOM, DTULTALTERACAO, QUA, QUI, SAB, SEG, SEX, TER, CODVENDEDOR, CODCLIENTE, CODFUNCAGEND);
-- Table: MANIFESTO_COMPLEMENTO
CREATE TABLE MANIFESTO_COMPLEMENTO (CODIGO, CODEMPRESA, ISCOMPLEMENTO, NUMCARGA, NUMPEDIDO, NUMPEDIDOORIGEM, ISPRINCIPAL, STATUS);
-- Table: GRUPOPISCOFINS
CREATE TABLE GRUPOPISCOFINS (CODIGO, DESCRICAO, DTULTALTERACAO);
-- Table: PESSOA3
CREATE TABLE PESSOA3 (CODIGO, NOME, FANTASIA, ENDERECO, IE, CNPJ, EMAIL, CIDADE, UF, TELEFONE, CEP, ATIVO, BAIRRO, BAIRROCOBRANCA, BAIRROENTREGA, BLOQATRASO, BLOQCHD1, BLOQCHD3, BLOQCHDV, BLOQUEADO, CATEGORIA, CELULAR, CELCOBRANCA, CELENTREGA, CEPCOBRANCA, CEPENTREGA, COMENTARIO, COMISSAO, COMPLEMENTO, COMPCOBRANCA, COMPENTREGA, CONTATO, CRC, DADOSBANCARIO, DTADMISSAO, DTBLOQUEIO, DTCADASTRO, DTNASCIMENTO, DTULTALTERACAO, DTULTCOMPRA, DTVENCIMENTO, EMAILBOLETO, EMAILCOBRANCA, EMAILENTREGA, ENDCOBRANCA, ENDENTREGA, ISUF, IDESTRANGEIRO, ISCLIENTE, ISCOLABORADOR, ISFORNECEDOR, ISMOTORISTA, ISTRANSPORTADORA, JUROS, MOTIVOBLOQUEIO, NUMAPOLICE, NUMAVERBACAO, NUMCNH, NUMREGISTRO, NUMERO, NUMCOBRANCA, NUMENTREGA, PRAZOENTREGA, RNTRC, SENHA, STATUSALTERACAO, STATUSFV, TELCOBRANCA, TELENTREGA, TIPOMOTORISTA, TIPOPESSOA, USUARIO, VLCREDDISPONIVEL, VLCREDUTILIZADO, VLLIMITECRED, CODCIDADE, TempCODCIDADE, CODCIDADECOBRANCA, CODCIDADEENTREGA, CODCOBRANCA, CODRAMOATIVIDADE, CODEMPRESA, CODNIVELACESSO, CODPLANOPGTO, CODREGIAO, CODSEGNIVELACESSO, CODSETOR, CODTABELA, TIPOCALCULO, CODVENDEDOR, CODVENDEDOR2, CODVENDEDOR3, CODVENDEDOR4, COBRANCAPERSONALIZADA, LATITUDE, LONGITUDE);
-- Table: PRECADASTROPESSOA
CREATE TABLE PRECADASTROPESSOA (CODIGO, ATIVO, BAIRRO, BLOQATRASO, BLOQCHD1, BLOQCHD3, BLOQCHDV, BLOQUEADO, CELULAR, CEP, CNPJ, CODCIDADE, CODEMPRESA, CODREGIAO, CODTABELA, CODVENDEDOR, COMENTARIO, COMPLEMENTO, CONTATO, DTNASCIMENTO, EMAIL, ENDERECO, ENVIOCHECKOUT, FANTASIA, IE, NOME, NUMERO, STATUSALTERACAO, STATUSFV, TELEFONE, TIPOCALCULO, TIPOPESSOA);
-- Table: CONTROLECAIXA_CARGAITENS
CREATE TABLE CONTROLECAIXA_CARGAITENS (CODIGO, CODPRODUTO, QTPEDIDA, NUMCARGA);
-- Table: UTILCREDITOFIS
CREATE TABLE UTILCREDITOFIS (ID, CHVDOCE, NRDOC, VLCREDUTIL, CONTROLECREDFIS, TIPOUTIL);
-- Table: AGENDAMENTOVISITANUMSEMANA
CREATE TABLE AGENDAMENTOVISITANUMSEMANA (CODIGO, NUMSEMANA, CODCLIENTE, CODVENDEDOR);
-- Table: MARCA
CREATE TABLE MARCA (CODIGO, NOME);
-- Table: VW_CONTROLE_BOLETO_BANCARIOS
CREATE TABLE VW_CONTROLE_BOLETO_BANCARIOS (CRECEBER_CODEMPRESA, CRECEBER_NUMNOTA, CRECEBER_NUMPARCELA, CRECEBER_TOTPARCELAS, CRECEBER_DTLANCAMENTO, CRECEBER_CODCOBRANCA, CRECEBER_VLORIGINAL, CRECEBER_VALOR, CRECEBER_PERDESCONTO, CRECEBER_VLDESCONTO, CRECEBER_PERJURO, CRECEBER_VLJURO, CRECEBER_DTVENCIMENTO, CRECEBER_DIASPRORROGADO, CRECEBER_DTPAGAMENTO, CRECEBER_VLPAGO, CRECEBER_DTBAIXA, CRECEBER_CODBANCO, CRECEBER_NUMCONTA, CRECEBER_NUMAGENCIA, CRECEBER_NUMCHEQUE, CRECEBER_CODMOEDA, CRECEBER_HISTORICO, CRECEBER_DTULTALTERACAO, CRECEBER_ALINEA, CRECEBER_NOSSONUMERO, CRECEBER_OBSERVACAO, CRECEBER_PROTOCOLO, CRECEBER_TIPOACOMPCOBRANCA, CRECEBER_DTCOBRANCA, CRECEBER_DTPREVPAGAMENTO, CRECEBER_OBSCOBRANCA, CRECEBER_STATUS, CRECEBER_NUMLANCAMENTO, CRECEBER_NUMREMESSA, CRECEBER_DTFECHA, CRECEBER_NUMDOCUMENTO, CRECEBER_DTVENCORIGINAL, CRECEBER_DTDESD, CRECEBER_CODCXBCO, CRECEBER_NUMCARGA, CRECEBER_SEUNUMERO, CRECEBER_DTBOLETO, CRECEBER_GEROUREMESSA, CRECEBER_CODSOLICAPICOBRANCA, CRECEBER_PIXCOPIAECOLA, CRECEBER_PIXTXID, FUNCBAIXA_CODIGO, FUNCBAIXA, EMPRESA_PERCJUROAUTOMATICO, EMPRESA_CNPJ, CRECEBER_NUMRECIBO, CRECEBER_STATUSBANCO, CRECEBER_CODCLIENTE, CLIENTE_NOME, CLIENTE_FANTASIA, CLIENTE_CNPJ, CXBANCO_NOME, SUBCUSTO_CODIGO, SUBCUSTO_SUBNIVEL, SUBCONTA_CODIGO, SUBCONTA_DESCRICAO, RESPCOB_CODIGO, RESPCOBRANCA_NOME, FUNCLANC_CODIGO, FUNCLANC_NOME, FUNCDESD_CODIGO, FUNCDESD_NOME, NUMSAIDA, NF_NUMPEDVENDA, NF__MODELO, COBRANCA_DESCRICAO, COBRANCA_TIPOCOBRANCA, CLIENTE_CODRAMOATIVIDADE, STATUS_CONCILIACAO);
-- Table: PRECO_ESTOQUE
CREATE TABLE PRECO_ESTOQUE (CODEMPRESA, CODPRODUTO, CUSTOMANUAL, CUSTOMEDIO, CUSTOULTENTRADA, PERCOMISSAO, PRECOREVENDA, QTBLOQUEADA, QTDISPONIVEL, QTESTOQUE, QTESTOQUEMINIMO, QTPENDENTE, QTRESERVADA, EMPRESA, CODGRUPOICMS, CODGRUPOIPI, CODGRUPOPISCOFINS, PRODUTO, DTULTALTERACAO, USAESTLOTE);
-- Table: IBPT
CREATE TABLE IBPT (ID, ESTADUAL, IMPORTADOSFEDERAL, MUNICIPAL, NACIONALFEDERAL, CHAVE, CODIGO, DESCRICAO, EX, VIGENCIAFIM, FONTE, VIGENCIAINICIO, TIPO, VERSAO);
-- Table: CONTROLECAIXA_CLIENTE
CREATE TABLE CONTROLECAIXA_CLIENTE (CODIGO, CODCLIENTE, CODEMPRESA, CODPRODUTO, QTCLIENTE);
-- Table: VEICULO
CREATE TABLE VEICULO (CODIGO, CAPACIDADEKG, CAPACIDADEM3, DESCRICAO, PLACA, RENAVAM, TARA, TIPOCARROCERIA, TIPOPROPRIETARIO, TIPOPROPRIETARIOVEIC, TIPORODADO, TIPOVEICULO, CODCIDADE, PROPRIETARIO, CONSUMOPORKM, TIPOCOMBUSTIVEL);
-- Table: AJUSTEAPURACAOICMS
CREATE TABLE AJUSTEAPURACAOICMS (ID, DESCRICAOCOMPLAJ, DTLANCAMENTO, VLAJAPUR, CODAJAPUR, CODEMPRESA);
-- Table: MDE
CREATE TABLE MDE (ID, CHAVENFE, CNPJEMIT, CODSTATUSMDE, CODSITNFE, DESCSTATUSMDE, DTEMISSAONFE, DTRECBTONFE, IEEMIT, JUSTIFICATIVA, NOMEEMIT, NSU, NUMPROTOCOLO, NUMNFE, SERIENFE, STATUS, TPAMB, TPNF, VLDOC, CODEMPRESA, LANCADA, CODFUNCMAN, DTLANCMDE, MOTIVOMAN);
-- Table: PRECOREGIAO
CREATE TABLE PRECOREGIAO (CODPRECOREGIAO, CPV, DTULTALTERACAO, DTVALIDADEPRECOOFERTA, PERCOMISSAO, PERDESCONTO, PERICMSCPV, PERMARGEMLUCRO, PEROPERACIONAL, PERPISCOFINSCPV, PERSIMPLESNACIONAL, PRECOMINIMO, PRECOOFERTA, PRECOOFERTAATIVO, VLFRETEPRODUTO, VLFRETETONELADA, PRECOCONSUMIDOR, PRECOREVENDA, PRECOSUGERIDO, CODFUNCULTALT, CODEMPRESAPRECO, CODPRODUTOPRECO, CODREGIAO);
-- Table: ICMSSTRETIDO_PRODUTO
CREATE TABLE ICMSSTRETIDO_PRODUTO (CODIGO, PERICMSST, VLBCSTRET, VLICMSSUBSTITUTO, VLSTRET, CODEMPRESA, CODPRODUTO);
-- Table: CONTROLECAIXA_MOV
CREATE TABLE CONTROLECAIXA_MOV (CODIGO, CODCLIENTE, CODEMPRESA, CODFUNCLANC, CODPRODUTO, DTMOV, NUMCARGA, QTMOV, ROTINA, STATUS, TIPOMOV);
-- Table: AJUSTEDOCFISCAL
CREATE TABLE AJUSTEDOCFISCAL (ID, ALIQICMS, DESCRCOMPLAJ, VLBCICMS, VLICMS, VLOUTROS, CODAJ, CODITEM, CODOBS, CODEMPRESA, NUMENTRADA, NUMSAIDA);
-- Table: MDE_TESTE
CREATE TABLE MDE_TESTE (ID, CHAVENFE, CNPJEMIT, CODSTATUSMDE, CODSITNFE, DESCSTATUSMDE, DTEMISSAONFE, DTRECBTONFE, IEEMIT, JUSTIFICATIVA, NOMEEMIT, NUMNFE, SERIENFE, STATUS, TPNF, VLDOC, CODEMPRESA);
-- Table: PRECOTABELA
CREATE TABLE PRECOTABELA (CODPRECOTAB, CPV, DTULTALTERACAO, DTVALIDADEPRECOOFERTA, PERCOMISSAO, PERDESCONTO, PERICMSCPV, PERMARGEMLUCRO, PEROPERACIONAL, PERPISCOFINSCPV, PERSIMPLESNACIONAL, PRECOMINIMO, PRECOOFERTA, PRECOOFERTAATIVO, VLFRETEPRODUTO, VLFRETETONELADA, PRECOCONSUMIDOR, PRECOREVENDA, PRECOSUGERIDO, CODFUNCULTALT, CODEMPRESAPRECO, CODPRODUTOPRECO, CODTABELA);
-- Table: CONTROLECREDITOFIS
CREATE TABLE CONTROLECREDITOFIS (ID, CREDAPR, CREDRECEB, CREDUTIL, DTLANCAMENTO, SLDCRED, SLDCREDFIM, CODAJAPUR, CODEMPRESA);
-- Table: VEICULO_COMPLEMENTOS
CREATE TABLE VEICULO_COMPLEMENTOS (ATIVO, GESTORENTREGA, CODVEICULO);
-- Table: ALIANCACARGA
CREATE TABLE ALIANCACARGA (DTENVIO, DTRETORNO, STATUS, NUMCARGA);
-- Table: MDFE
CREATE TABLE MDFE (NUMMDFE, CHAVEACESSO, CODCHAVEACESSOMDFE, CODSTATUSMDFE, CODUNID, DESCSTATUSMDFE, DTAUTORIZACAO, DTCANCELAMENTO, DTEMISSAO, DTENCERRAMENTO, DTTRANSMISSAO, MODAL, MODELO, NUMLOTE, NUMMANIFESTO, NUMPROTOCOLO, NUMRECIBO, OBS, OBSFISCO, QTCTE, QTNFE, SERIE, TPAMB, TIPODOCMDFE, TPEMIS, TPEMIT, TOTPESOBRUTO, VLTOTAL, CODEMPRESA, UFCARREGAMENTO, UFDESCARREGAMENTO, CODVEICULO, MOTIVOCANC, CODFUNCCANC, DTINIVIAGEM, INFMANUALCONDUTORCNPJCPF, INFMANUALCONDUTOR, INFMANUALVEICULOPLACA, INFMANUALVEICULORENAVAM, INFMANUALVEICULOTARA, INFMANUALVEICULOTIPORODADO);
-- Table: IEST
CREATE TABLE IEST (id, IE, CODEMPRESA, UF);
-- Table: PREDEV
CREATE TABLE PREDEV (NUMPREDEV, DTEMISSAO, MODELO, QTITENS, STATUS, TOTPESOBRUTO, TOTPESOLIQUIDO, VLTOTDEV, VLTOTITENS, CODCLIENTE, CODCOBRANCA, CODEMPRESA, CODNATOPERACAO, NUMENTRADA, NUMPEDIDOORIGEM, CODPLANOPGTO, CODVENDEDOR);
-- Table: CONTROLEVERSAOVIEW
CREATE TABLE CONTROLEVERSAOVIEW (NOME, VERSAO);
-- Table: VENDEDOR
CREATE TABLE VENDEDOR (CODIGO, BAIRRO, CELULAR, CEP, CNPJCPF, COMPLEMENTO, DTADMISSAO, DTCADASTRO, DTULTALTERACAO, EMAIL, ENDERECO, NOME, NUMERO, PERCOMISSAO, RG, TELEFONE, TIPOCOMISSAO, CODCIDADE, CODSUPERVISOR);
-- Table: ALIANCAPEDIDO
CREATE TABLE ALIANCAPEDIDO (CODIGO, DTENVIO, NUMPEDIDOALIANCA, STATUS, NUMPEDIDO);
-- Table: METAVENDEDORCATEGORIA
CREATE TABLE METAVENDEDORCATEGORIA (CODIGO, DTFIM, DTINICIO, QTDIASUTEIS, QTMETACATEGORIA, CODCATEGORIA, CODDEPARTAMENTO, CODEMPRESA, CODSECAO, CODVENDEDOR);
-- Table: IMPOSTOIMPORTACAO
CREATE TABLE IMPOSTOIMPORTACAO (ID, VBC, VDESPADU, VIOF, VII, IDMOV);
-- Table: PREDEV_ITEM
CREATE TABLE PREDEV_ITEM (ID, QTDEVOLVIDA, SUBTOTAL, SUBTOTALORIG, TOTPESOBRUTO, TOTPESOLIQUIDO, VLUNITARIO, NUMPREDEV, CODPRODUTO, VLICMSST, VLIPI);
-- Table: CPFNANOTA
CREATE TABLE CPFNANOTA (CODIGO, CPF, INFADICIONAIS, NOME, NUMSAIDA);
-- Table: VENDEDOR_COMPLEMENTOS
CREATE TABLE VENDEDOR_COMPLEMENTOS (ATIVO, CODVENDEDOR, PERMITEDESCSEMSALDOFLEXIVEL, TIPOMOVFLEXIVEL, USAFLEXIVEL, VLLIMCREDFLEX, VLSALDOFLEX);
-- Table: METAVENDEDORPRODUTO
CREATE TABLE METAVENDEDORPRODUTO (CODIGO, QTMETAPRODUTO, CODMETAVENDCATEGORIA, CODPRODUTO);
-- Table: INACESSOLIBERADO
CREATE TABLE INACESSOLIBERADO (ISLIBERADO, CODCOLABORADOR);
-- Table: ALIANCAPEDIDO_ITEM
CREATE TABLE ALIANCAPEDIDO_ITEM (CODIGO, CODBARRA, CONFIRMADO, DESCRICAO, FALTA, PRECO, QTPEDIDA, NUMPEDIDO);
-- Table: PREDEV_ITEM_OCORRENCIA
CREATE TABLE PREDEV_ITEM_OCORRENCIA (CODIGO, QUANTIDADE, CODITEM, CODOCORRENCIA);
-- Table: CREDCLIENTE
CREATE TABLE CREDCLIENTE (NUMLANCAMENTO, BAIXADO, DTBAIXA, DTESTORNO, DTLANCAMENTO, NUMNOTA, VALORTOTAL, VLBAIXADO, VLSALDO, CODCLIENTE, CODFUNCBAIXA, CODFUNCESTORNO, CODFUNCLANC, CODEMPRESA, NUMSAIDA, TITULOORIG, DTCANCELAMENTO, CODFUNCCANCELAMENTO, CODCXBCO, CODMOEDA, NUMENTRADA);
-- Table: VENDEDOR_EMPRESAS
CREATE TABLE VENDEDOR_EMPRESAS (CODVENDEDOR, CODEMPRESA, CODCXBCO);
-- Table: METAVENDEDORVALOR
CREATE TABLE METAVENDEDORVALOR (CODIGO, DTFIM, DTINICIO, QTDIASUTEIS, VALORMETA, CODEMPRESA, CODVENDEDOR);
-- Table: INEMPRESA
CREATE TABLE INEMPRESA (CODIGO, MARGEMLUCROMAXIMA, MARGEMLUCROMINIMA, PARAMETRIZOUMARGEMLUCRO, CODEMPRESA);
-- Table: VENDEDOR_NATUREZAS
CREATE TABLE VENDEDOR_NATUREZAS (CODVENDEDOR, CODNATOPERACAO);
-- Table: ALIQICMS
CREATE TABLE ALIQICMS (CODIGO, PERICMS, UFDEST, UFORIG);
-- Table: PREDEV_OCORRENCIA
CREATE TABLE PREDEV_OCORRENCIA (CODIGO, DESCRICAO);
-- Table: CREDCLIENTE_NF
CREATE TABLE CREDCLIENTE_NF (NUMLANCAMENTO, VLBAIXA, NUMCREDITO, NUMSAIDA, ESTORNADO);
-- Table: VERSAOSISTEMA
CREATE TABLE VERSAOSISTEMA (ID, DTATUALIZACAO, NOMECOMPUTADOR, VERSAOERP);
-- Table: MOD_SUBMOD
CREATE TABLE MOD_SUBMOD (CODMOD, CODSUBMOD);
-- Table: INFADAPURACAOICMS
CREATE TABLE INFADAPURACAOICMS (ID, DESCRICAOCOMPLAJ, DTLANCAMENTO, VLINFADIC, CODINFADIC, CODEMPRESA);
-- Table: APURACAOICMS
CREATE TABLE APURACAOICMS (DTFIM, DTINICIO, CODREC, DTVENCIMENTO, VLAJCREDITOS, VLAJDEBITOS, VLTOTAJCREDITOS, VLTOTAJDEBITOS, VLTOTCREDITOS, VLTOTDEBITOS, VLTOTDED, VLESTORNOSCRED, VLESTORNOSDEB, VLICMSRECOLHER, DEBESP, VLSLDCREDORANT, VLSLDCREDORTRANSPORTAR, VLSLDAPURADO, CODEMPRESA, CODOBRIGACAOREC);
-- Table: PROCADMINPISCOFINS
CREATE TABLE PROCADMINPISCOFINS (ID, DTDECADMN, INDNATACAO, NUMPROC, CODEMPRESA);
-- Table: CREDIARIOPROPRIO
CREATE TABLE CREDIARIOPROPRIO (CARGO_PESSOA, CONJUGECARGO, CONJUGECPF, CONJUGEENDLOCTRAB, CONJUGEFONE, CONJUGEFONELOCTRAB, CONJUGENOME, CONJUGELOCTRAB, EMPRESA_PESSOA, END_EMP_PESSOA, FONE_EMP_PESSOA, MAE, PAI, REFCOMERCIALNOME1, REFCOMERCIALTEL1, REFCOMERCIALNOME2, REFCOMERCIALTEL2, REFPESSOALNOME1, REFPESSOALTEL1, REFPESSOALNOME2, REFPESSOALTEL2, RG, CODPESSOA);
-- Table: MODALIDADEBASECALCULO
CREATE TABLE MODALIDADEBASECALCULO (ID, CODIGO, DESCRICAO);
-- Table: INFDOCMDFE
CREATE TABLE INFDOCMDFE (ID, CHAVEACESSODOC, PESOTOTALDOC, VLTOTALDOC, CODCIDADEDESCARGA, NUMTRANSPORTE, NUMMDFE, NUMSAIDA);
-- Table: APURACAOICMSST
CREATE TABLE APURACAOICMSST (DTFIM, DTINICIO, UF, DEBESPST, VLAJCREDITOSST, VLAJDEBITOSST, VLDEDUCOESST, VLDEVOLST, VLICMSRECOLST, VLOUTCREDST, VLOUTDEBST, VLRESSARCST, VLRETENCAOST, VLSLDCREDANTST, VLSLDCREDSTTRANSPORTAR, VLSLDDEVANTST, CODEMPRESA, CODREC, DTVENCIMENTO, CODOBRIGACAOREC);
-- Table: PRODPREDMDFE
CREATE TABLE PRODPREDMDFE (ID, CEAN, NCM, TPCARGA, XPROD, NUMMDFE);
-- Table: CREDITOCOFINS
CREATE TABLE CREDITOCOFINS (ID, ALIQCOFINS, ALIQCOFINSQUANT, CODCRED, DTFIM, DTINICIO, INDCREDORI, INDDESCCRED, QUANTBCCOFINS, SLDCRED, VLAJUSACRES, VLAJUSREDUC, VLBCCOFINS, VLCRED, VLCREDDESC, VLCREDDIF, VLCREDDISP, CODEMPRESA);
-- Table: MODALIDADEBASECALCULOST
CREATE TABLE MODALIDADEBASECALCULOST (ID, CODIGO, DESCRICAO);
-- Table: INFLOTACAOMDFE
CREATE TABLE INFLOTACAOMDFE (ID, CEPCARREGA, CEPDESCARREGA, PRODPRED);
-- Table: APURACAOIPI
CREATE TABLE APURACAOIPI (DTFIM, DTINICIO, VLCREDIPI, VLDEBIPI, VLOCIPI, VLODIPI, VLSCIPI, VLSDANTIPI, VLSDIPI, CODEMPRESA);
-- Table: PRODUTO
CREATE TABLE PRODUTO (CODIGO, ATIVO, CODBARRA, CODFABRICA, DTCADASTRO, DTULTALTERACAO, EXIPI, FTEMBALAGEM, INFADICIONAIS, NOME, PESOBRUTO, PESOLIQUIDO, TIPO, VOLUME, CATEGORIA, CODCEST, CLASSIFICACAO, DEPARTAMENTO, FABRICANTE, FORNECEDOR, GENERO, CODNCM, CODPRODPRINC, SECAO, UNIDADE, STATUS, DIASVALIDADE, METROCUBICO, MARCA, ACEITAVENDAFRACIONADA, OBSERVACAO, ISPRODUTOCOMBO, ISPRODUTOPESADO);
-- Table: CREDITOPIS
CREATE TABLE CREDITOPIS (ID, ALIQPIS, ALIQPISQUANT, CODCRED, DTFIM, DTINICIO, INDCREDORI, INDDESCCRED, QUANTBCPIS, SLDCRED, VLAJUSACRES, VLAJUSREDUC, VLBCPIS, VLCRED, VLCREDDESC, VLCREDDIF, VLCREDDISP, CODEMPRESA);
-- Table: MODULO
CREATE TABLE MODULO (CODIGO, NOME);
-- Table: INVENTARIO
CREATE TABLE INVENTARIO (CODIGO, CODCTA, DTINVENTARIO, INDPROP, QUANTIDADE, TXTCOMPL, VLITEMIR, VLITEM, VLUNIT, CODEMPRESA, CODPRODUTO, CODUNIDADE);
-- Table: ATENDIMENTOVISITACLIENTE
CREATE TABLE ATENDIMENTOVISITACLIENTE (CODIGO, DTATENDIMENTO, LATITUDE, LONGITUDE, OBSERVACAO, CODCLIENTE, NUMPEDVENDA, CODVENDEDOR);
-- Table: PRODUTO_COMPLEMENTOS
CREATE TABLE PRODUTO_COMPLEMENTOS (ISGTIN, OBSERVACAO2, PERMITEINFQTCONF, CODPRODUTO, APELIDO, ENVIAECOMERCI, INFNUTRICIONAL, ISCOMODATO, METROQUADRADO, QTUNCX, UNTRIBCODBARRA, UNTRIBUNIDADE, VOLUMENOTAFISCAL);
-- Table: CRMAGENDAMENTO
CREATE TABLE CRMAGENDAMENTO (CODIGO, DTAGEND, DTCONTATO, MOTIVOAGEND, STATUS, TIPOCONTATO, CODCRMHISTCONTATO, CODCLIENTE, CODFUNCLANC, CODVENDEDOR);
-- Table: MOEDA
CREATE TABLE MOEDA (CODMOEDA, NOME);
-- Table: INVENTARIOCOLABORADORMOBILE
CREATE TABLE INVENTARIOCOLABORADORMOBILE (IDENTIFICADORMOBILE, TIPOBUSCAPRODUTO, CODCOLABORADOR, CODCATEGORIA, CODDEPARTAMENTO, CODEMPRESA, CODSECAO);
-- Table: BANCO
CREATE TABLE BANCO (CODIGO, CODBANCO, NOME);
-- Table: PRODUTO_FORNECEDOR
CREATE TABLE PRODUTO_FORNECEDOR (CODIGO, CODIGOPRODFORNECEDOR, FATORCONVERSAO, CODIGOFORNECEDOR, CODIGOPRODUTO);
-- Table: CRMHISTCONTATO
CREATE TABLE CRMHISTCONTATO (CODIGO, DTCONTATO, HISTORICO, TIPOCONTATO, CODCLIENTE, CODFUNCLANC, CODVENDEDOR);
-- Table: INVENTARIOCOLABORADORPRODUTOS
CREATE TABLE INVENTARIOCOLABORADORPRODUTOS (ID, CODCOLABORADOR, CODPRODUTO);
-- Table: MOV_ESTOQUELOTE
CREATE TABLE MOV_ESTOQUELOTE (CODIGO, CODESTLOTE, CODFUNCLANC, CODITEMPCP, CODITEMPED, CODMOV, DTMOV, QUANTIDADE, ROTINA, STATUS, TIPOOPERACAO, QTCONFERENCIA);
-- Table: CSOSN
CREATE TABLE CSOSN (ID, CODIGO, DESCRICAO);
-- Table: BANDEIRASITEF
CREATE TABLE BANDEIRASITEF (CODIGO, BANDEIRA, DETALHAMENTO, SUBTIPO, TIPO, DTULTALTERACAO, CODCOBRANCA);
-- Table: PRODUTO2
CREATE TABLE PRODUTO2 (CODIGO, NOME, ATIVO, CODBARRA, CODFABRICA, DTCADASTRO, DTULTALTERACAO, EXIPI, FTEMBALAGEM, INFADICIONAIS, PESOBRUTO, PESOLIQUIDO, TIPO, VOLUME, CATEGORIA, CODCEST, CLASSIFICACAO, DEPARTAMENTO, FABRICANTE, FORNECEDOR, GENERO, CODNCM, CODPRODPRINC, SECAO, UNIDADE, STATUS, DIASVALIDADE, METROCUBICO, MARCA, ACEITAVENDAFRACIONADA, OBSERVACAO, ISPRODUTOCOMBO, ISPRODUTOPESADO, PRECO1, PRECO2, PRECO3, PROD_ID);
-- Table: INVENTARIOK200
CREATE TABLE INVENTARIOK200 (CODIGO, CODCTA, DTINVENTARIO, INDPROP, QUANTIDADE, TXTCOMPL, VLITEMIR, VLITEM, VLUNIT, CODEMPRESA, CODPRODUTO, CODUNIDADE);
-- Table: PRODUTOCOMBO
CREATE TABLE PRODUTOCOMBO (CODIGO, DTCADASTRO, DTULTALTERACAO, CODPRODUTO);
-- Table: MOVCXBCO
CREATE TABLE MOVCXBCO (NUMTRANSACAO, CONCILIADO, DTCONCILIACAO, DTMOVIMENTACAO, DTPAGAMENTO, HISTORICO, HISTORICO2, NUMDOC, TIPO, TIPOMOV, VALOR, VLSALDO, VLSALDOCONCILIADO, CODCXBCO, CODEMPRESA, CODMOEDA, CODUSRCONC, CODUSRMOV, CODOPERADORPDV);
-- Table: CST
CREATE TABLE CST (ID, CODIGO, DESCRICAO);
-- Table: BEMINCATIVOIMOBILIZADO
CREATE TABLE BEMINCATIVOIMOBILIZADO (ID, ALIQCOFINS, ALIQPIS, CODCCUS, CODCTA, CSTCOFINS, CSTPIS, DESCBEMIMOB, DTOPER, IDENTBEMIMOB, INDORIGCRED, INDUTILBEMIMOB, NATBCCRED, PARCOPERNAOBCCRED, VLBCCOFINS, VLBCPIS, VLCOFINS, VLOPERDEP, VLPIS, CODEMPRESA);
-- Table: ITAUEIRACLASSIFICACAO
CREATE TABLE ITAUEIRACLASSIFICACAO (CODITAUEIRA, DESCRICAOITAUEIRA, CODRAMOATIVIDADE);
-- Table: MOVIMENTACAO
CREATE TABLE MOVIMENTACAO (ID, CODUNIDADE, CUSTOMEDIO, CUSTOREAL, CUSTOULTENTRADA, DTMOVIMENTACAO, ENQUADRAMENTOIPI, FTCONVERTE, NUMNOTA, OBSITEM, OPERACAO, PERDESCONTO, PERBASECALCULOCOFINS, PERBASECALCULOICMS, PERBASECALCULOICMSST, PERBASECALCULOIPI, PERBASECALCULOPIS, PERBASECALCULOSTCOFINS, PERBASECALCULOSTPIS, PERCOFINS, PERCOMISSAO, PERCENTUALCREDSIMPLES, PERCENTUALDIFERIMENTO, PERCENTUALFCP, PERCENTUALICMS, PERCENTUALICMSINTERDEST, PERCENTUALICMSINTERPART, PERCENTUALICMSINTERESTADUAL, PERCENTUALICMSST, PERCENTUALINTERNO, PERCENTUALIPI, PERCENTUALMVA, PERPIS, PERSTCOFINS, PERSTPIS, PESOBRUTO, PESOLIQUIDO, QTCONVERTIDA, QTDEVOLVIDA, QTORIGINAL, QUANTIDADE, SEQITEM, STATUS, SUBTOTAL, SUBTOTALORIG, SUBTOTALTARIFAINTERNA, VALORTOTTRIB, VALORTOTTRIBESTADUAL, VALORTOTTRIBFEDERAL, VALORTOTTRIBMUNICIPAL, VALORBASECOFINS, VALORBASEICMS, VALORBASEICMSST, VALORBASEICMSUFDEST, VALORBASEIPI, VALORBASEPIS, VALORBASESTCOFINS, VALORBASESTPIS, VALORCOFINS, VLCOMISSAO, VALORCREDSIMPLES, VALORICMDIFERIMENTO, VALORICMINTERNO, VALORICMS, VALORICMSST, VALORIPI, VALORMVA, VALORPIS, VALORSTCOFINS, VALORSTPIS, VLDESCONTO, VALORFCPDEST, VLFRETE, VLFRETEFNOTA, VLICMSDESON, VALORICMSUFDEST, VALORICMSUFREMET, VLOUTRASDESP, VLSEGURO, VLTARIFA, VLTARIFAINTERNA, VALORUNIDADEIPI, VLUNITARIO, CFOP, CSOSN, CST, CSTCOFINS, CSTIPI, CSTPIS, NUMTRANSPORTE, CODEMBALAGEM, CODEMPRESA, CODFUNCIONARIO, CODITEMPEDVENDA, MODALIDABEBCICMS, MODALIDABEBCICMSST, NUMENTRADA, NUMSAIDA, NUMOP, CODFORMULA, CODEMPRESAINVENTARIO, NUMINVENTARIO, ORIGMERCADORIA, NUMPEDIDOVENDA, CODEMPRESAPRECO, CODPRODUTOPRECO, CODPRECOREGIAO, CODPRECOTABELA, CODPRODUTO, CODCONTA, VALORBASEICMSSTRET, VLFCP, VLFCPST, VLFCPSTRET, VALORICMSSTRET, CODBENEF, VALORICMSSUBSTITUTO, VLOUTRASFNOTA, PERDESCONTOCOFINS, PERDESCONTOPIS, PERCENTUALFCPST, PERCENTUALIRRF, VALORBASEFCPST, VALORIRRF, VLDESCONTOCOFINS, VLDESCONTOPIS, VOLUMEITEM);
-- Table: CSTIPI
CREATE TABLE CSTIPI (ID, CODIGO, DESCRICAO, TIPOMOVIMENTO);
-- Table: CABPEDCOMPRA
CREATE TABLE CABPEDCOMPRA (NUMPEDIDO, DTCANCELAMENTO, DTEMISSAO, DTPREVENTREGA, DTULTALTERACAO, FRETEPORCONTA, MOTIVOCANC, OBSERVACAO, PERDESCCOMPRA, QTITENS, STATUS, TIPOCOMPRA, TIPOFRETE, TOTPESOBRUTO, TOTPESOLIQUIDO, VLDESCCOMPRA, VLFRETE, VLOUTRASDESP, VLSEGURO, VLTOTIPI, VLTOTCOMPRA, VLTOTICMSST, VLTOTITENS, VLTOTRESTANTE, CODCOBRANCA, CODCOMPRADOR, CODFUNCALTERACAO, CODFUNCCANC, CODEMPRESA, CODFORNECEDOR, CODPLANOPGTO, CODTRANSPORTADORA, DTCONFERENCIA, STATUSCONFERENCIA);
-- Table: PRODUTOCOMBOITENS
CREATE TABLE PRODUTOCOMBOITENS (CODIGO, QUANTIDADE, CODPRODUTOCOMBO, CODPRODUTO);
-- Table: ITAUEIRADEPARAPRODUTO
CREATE TABLE ITAUEIRADEPARAPRODUTO (FTCONVERSAO, CODPRODUTO, CODPRODITAUEIRA);
-- Table: NATOPERACAO
CREATE TABLE NATOPERACAO (CODIGO, ALTERACUSTO, ATIVO, BAIXAESTOQUE, DESCRICAO, DTALTERACAO, DTINCLUSAO, FINALIDADE, GERAFINANC, STATUSFV, UTILIZACAO);
-- Table: CSTPISCOFINS
CREATE TABLE CSTPISCOFINS (ID, CODIGO, DESCRICAO, TIPOMOVIMENTO);
-- Table: CABPEDVENDA
CREATE TABLE CABPEDVENDA (NUMPEDIDO, DTCANCELAMENTO, DTEMISSAO, DTLIBERACAO, DTPREVENTREGA, DTSAIDA, DTULTALTERACAO, ESPECIEVOLUME, FRETEPORCONTA, ISEDICAO, ISFATURADO, MARCAVOLUME, MODELO, MOTIVOCANC, MOTIVOBLOQ, NUMPEDIDOFV, NUMPEDIDOORIGEM, NUMEROVOLUME, OBSERVACAO, OBSPEDIDO, PERDESCVENDA, QTITENS, SEQ, SERIE, STATUS, TIPOFRETE, TIPOVENDA, TIPOPAGAMENTO, TOTPESOBRUTO, TOTPESOLIQUIDO, TOTVOLUME, VLCREDCLIENTE, VLDESCVENDA, VLFRETE, VLOUTRASDESP, VLSEGURO, VLTOTIPI, VLTOTTRIBESTADUAL, VLTOTTRIBFEDERAL, VLTOTTRIBMUNICIPAL, VLTOTBASEICMS, VLTOTBASEICMSST, VLTOTCOFINS, VLTOTENTREGUE, VLTOTICMS, VLTOTICMSST, VLTOTITENS, VLTOTNOTA, VLTOTPIS, VLTOTRESTANTE, VLTOTRIBUTOS, NUMCARGA, CODCLIENTE, CODCOBRANCA, CODFUNCALTERACAO, CODFUNCCANC, CODFUNCLANC, CODFUNCLIB, CODCPFNANOTA, CODEMPRESA, CODNATOPERACAO, CODPLANOPGTO, CODTRANSPORTADORA, CODVENDEDOR, DTCONFERENCIA, STATUSCONFERENCIA, CODFUNCCONF);
-- Table: PRODUTOLAUDO
CREATE TABLE PRODUTOLAUDO (CODIGO, NOME, OBSPADRAO, RESULTADO, VALORINDICADO, CODPRODUTO);
-- Table: ITAUEIRAPRODUTO
CREATE TABLE ITAUEIRAPRODUTO (CODITAUEIRA, DESCRICAOITAUEIRA);
-- Table: CTE
CREATE TABLE CTE (NUMTRANSACAO, BASECALCULO, VLBASECOFINS, VLBASEPIS, CHAVEACESSO, CHAVEACESSOCOMP, CODSTATUSCTE, CST, DESCCODSTATUSCTE, DTAUTORIZACAO, DTCANCELAMENTO, DTDECLARACAO, DTINUTI, DTLANCAMENTO, FORMAPGTO, IDGERALOTE, IDLOTE, IMPRESSO, MODELO, MOTIVOCANCEL, NUMCTE, NUMLOTE, NUMPROTOCOLO, NUMRECIBO, OBSERVACAO, OUTRASCARACTERISTICA, PFCPUFFIM, PICMSINTER, PICMSINTERPART, PICMSUFFIM, PERCOFINS, PERICMS, PERPIS, PERREDBASECALCULO, PESOBRUTO, DTPREVENTREGA, PRODPREDOMINANTE, RESPSEGURO, SEQEVT, SERIE, TIPOCTE, TIPODATA, TIPOEMISSAO, TIPOIMPRESSAO, TIPOSERVICO, TOMADORSERV, VBCUFFIM, VFCPUFFIM, VICMSUFFIM, VICMSUFINI, VLCARGA, VLCOFINS, VLFRETE, VLICMS, VLPIS, CODCFOP, CIDADEFIM, CIDADEINICIO, CODFUNCCANCELAMENTO, CODFUNCINUTLIZACAO, CODFUNCLANCAMENTO, DESTINATARIO, CODEMPRESA, EXPEDIDOR, CODMOTORISTA, CODPLANOPGTO, RECEBEDOR, REMETENTE, SEGURADORA, CHAVEACESSOCTEORIGINAL, CHAVEACESSONFETOMADOR, NUMAPOLICE, NUMAVERBACAO, VLPEDAGIOFRETE);
-- Table: CABPEDVENDA_COMPLEMENTOS
CREATE TABLE CABPEDVENDA_COMPLEMENTOS (DTCANCCONF, NUMOP, NUMPEDIDO, CODFUNCCANCCONF, NUMPEDCOMPRA, NUMPEDECOMMERCE, APPORIGEM, VLTOTFCPST, VLTOTICMSDESON);
-- Table: PRODUTOTABTECNICANUTRICIONAL
CREATE TABLE PRODUTOTABTECNICANUTRICIONAL (CODIGO, QTCOMPARATIVA, QTPORCAODESCRICAO, QTPORCAOVALOR, VLDIARIO, CODPRODUTO);
-- Table: NATRECEITAPISCOFINS
CREATE TABLE NATRECEITAPISCOFINS (ID, ALIQCOFINS, ALIQPIS, CODIGO, DESCRICAO, DTFIM, DTINICIO, EXIPI, NCM, NCMEX, TABELA, UNIDADE);
-- Table: ITEMCARTACORRECAOCTE
CREATE TABLE ITEMCARTACORRECAOCTE (ID, CAMPO, GRUPO, NROITEM, VALOR, CODCORRECAO);
-- Table: CTE_COMPLEMENTOS
CREATE TABLE CTE_COMPLEMENTOS (ISGLOBALIZADO, NUMTRANSACAO);
-- Table: CABPEDVENDA_CONTASARECEBER
CREATE TABLE CABPEDVENDA_CONTASARECEBER (CODIGO, DTPAGAMENTO, DTSOLICITACAOPIX, PIXCOPIAECOLA, PIXREVISAO, PIXTXID, STATUS, VALOR, CODCXBCO, CODCOBRANCA, NUMPEDIDO, APIORIGEM);
-- Table: RAMOATIVIDADE
CREATE TABLE RAMOATIVIDADE (ID, DESCRICAO);
-- Table: NCM
CREATE TABLE NCM (CODIGO, DESCRICAO, DTULTALTERACAO);
-- Table: ITEMPEDCOMPRA
CREATE TABLE ITEMPEDCOMPRA (ID, PERDESCONTO, QTENTREGUE, QTPEDIDA, QTRESTANTE, SUBTOTAL, SUBTOTALORIG, TOTPESOBRUTO, TOTPESOLIQUIDO, VLICMSST, VLIPI, VLTOTENTREGUE, VLTOTRESTANTE, VLDESCONTO, VLFRETE, VLOUTRASDESP, VLSEGURO, VLUNITARIO, NUMPEDIDO, CODEMPRESAPRECO, CODPRODUTOPRECO, CODPRODUTO, DTCONFERENCIA, QTCONFERENCIA, CODFUNCCONFERENCIA);
-- Table: CTE_CPAGAR
CREATE TABLE CTE_CPAGAR (CODCTE, CODCPAGAR, NUMLANCAMENTO);
-- Table: CAIXA_TITULO
CREATE TABLE CAIXA_TITULO (CODCAIXA, CODTITULO);
-- Table: REBOQUEMDFE
CREATE TABLE REBOQUEMDFE (ID, NUMMDFE, CODVEICULO);
-- Table: NEGOCIACAO
CREATE TABLE NEGOCIACAO (CODIGO, ISAUTORIZADA, ISCANCELADO, DTALTERACAO, DTAUTORIZACAO, DTCANCELAMENTO, DTLANCAMENTO, ISENVIADOFV, ISFV, PERDESCONTO, ISUTILIZADO, PRECO, CODCLIENTE, CODFUNCALT, CODFUNCAUT, CODFUNCCANC, CODFUNCLANC, CODEMPRESA, CODPRODUTO, CUSTOMEDIONEG, MARGEMNEG, PRECOCONSUMIDORNEG);
-- Table: ITEMPEDVENDA
CREATE TABLE ITEMPEDVENDA (ID, PERCOMISSAO, PERDESCONTO, PERBASECALCULOCOFINS, PERBASECALCULOCOFINSST, PERBASECALCULOICMS, PERBASECALCULOICMSST, PERBASECALCULOIPI, PERBASECALCULOPIS, PERBASECALCULOPISST, PERCOFINS, PERCREDSIMPLES, PERICMS, PERICMSDIFERIMENTO, PERICMSINTERNO, PERICMSST, PERCENTUALIPI, PERMVA, PERPIS, PERSTCOFINS, PERSTPIS, QTENTREGUE, QTPEDIDA, QTRESTANTE, SEQUENCIA, STATUS, SUBTOTAL, SUBTOTALORIG, TOTPESOBRUTO, TOTPESOLIQUIDO, VALORTOTTRIB, VALORTOTTRIBESTADUAL, VALORTOTTRIBFEDERAL, VALORTOTTRIBMUNICIPAL, VALORBASECOFINS, VALORBASECOFINSST, VALORBASEICMS, VALORBASEICMSST, VALORBASEIPI, VALORBASEPIS, VALORBASEPISST, VALORCOFINS, VALORCREDSIMPLES, VALORICMS, VALORICMSDIFERIMENTO, VALORICMSINTERNO, VALORICMSST, VALORIPI, VALORMVA, VALORPIS, VALORSTCOFINS, VALORSTPIS, VALORTOTENTREGUE, VALORTOTRESTANTE, VLCOMISSAO, VLDESCONTO, VLFRETE, VLOUTRASDESP, VLSEGURO, VALORUNIDADEIPI, VLUNITARIO, VLVENDA, CFOP, CSOSN, CST, CSTCOFINS, CSTIPI, CSTPIS, CODEMBALAGEM, MODALIDADEBCICMS, MODALIDADEBCICMSST, NUMPEDIDO, ORIGEMMERCADORIA, CODEMPRESAPRECO, CODPRODUTOPRECO, CODPRECOREGIAO, CODPRECOTABELA, CODPRODUTO, DTCONFERENCIA, QTCONFERENCIA, CODFUNCCONFERENCIA, VALORBASEICMSSTRET, VALORICMSSTRET, TIPODESCONTO, VALORICMSSUBSTITUTO, VLUNITARIOORIG, OBSITEM, PERCENTUALFCPST, VALORBASEFCPST, VALORFCPST, VLICMSDESON, VOLUMEITEM);
-- Table: CAMPOALTERACAOCCECTE
CREATE TABLE CAMPOALTERACAOCCECTE (ID, CAMPO, DESCRICAO, IDGRUPO);
-- Table: RECISENTACOFINS
CREATE TABLE RECISENTACOFINS (ID, CODCTA, CSTCOFINS, DESCCOMPL, DTFIM, DTINICIO, VLTOTREC, CODEMPRESA);
-- Table: NEGOCIACAOPORPERIODO
CREATE TABLE NEGOCIACAOPORPERIODO (CODIGO, DTCANCELAMENTO, DTFIM, DTINICIO, DTLANCAMENTO, STATUS, VLDESCONTO, CODCLIENTE, CODFUNCCANC, CODFUNCLANC, CODEMPRESA, CODPRODUTO);
-- Table: ITEMREQCOMPRA
CREATE TABLE ITEMREQCOMPRA (ID, QTPEDIDA, TOTPESOBRUTO, TOTPESOLIQUIDO, NUMREQUISICAO, CODPRODUTO);
-- Table: CTE_CRECEBER
CREATE TABLE CTE_CRECEBER (CODCTE, CODCRECEBER, NUMLANCAMENTO);
-- Table: CARGA_PEDIDO
CREATE TABLE CARGA_PEDIDO (NUMCARGA, NUMPEDIDO);
-- Table: RECISENTAPIS
CREATE TABLE RECISENTAPIS (ID, CODCTA, CSTPIS, DESCCOMPL, DTFIM, DTINICIO, VLTOTREC, CODEMPRESA);
-- Table: NF
CREATE TABLE NF (ID, CHAVENF, NUMERODOC, SERIE, CTE, CFOP, DTEMISSAO, MODELO, PESOBRUTO, VLBASEICMS, VLBASEICMSST, VLICMS, VLTOTICMSST, VLTOTITENS, VLTOTNOTA);
-- Table: LOCALIDADE_DEPOSITO
CREATE TABLE LOCALIDADE_DEPOSITO (CODIGO, ATIVO, CODEMPRESA, DESCRICAO);
-- Table: CARREGAMENTO
CREATE TABLE CARREGAMENTO (NUMCARGA, DTCANCELAMENTO, DTCARREGAMENTO, DTFECHA, DTSAIDA, ISANDAMENTO, ISENTREGUE, ISROTERIZADO, OBSERVACAO, STATUS, TIPO, TOTPESOBRUTO, TOTPESOLIQUIDO, TOTVOLUME, VLTOTAL, CODFUNCCANCELA, CODFUNCMONTA, CODCIDADECOLETA, CODCIDADEDESTINO, CODEMPRESA, CODFUNCFAT, CODMOTORISTA, CODVEICULO, TOTMETROSCUB);
-- Table: CTE_MOV
CREATE TABLE CTE_MOV (CODCTE, CODMOV, ID);
-- Table: REDECLIENTE
CREATE TABLE REDECLIENTE (CODIGO, ATIVO, DESCRICAO);
-- Table: NFENTRADA
CREATE TABLE NFENTRADA (NUMENTRADA, ANOMESEMISSAONFPRODRURAL, CHAVEACESSO, CHAVEACESSONFEREF, CHVCTEREF, CNPJPRODUTORRURAL, CODCHAVEACESSONFE, CODCHAVEACESSONFE2, CODSTATUSNFE, DESCSTATUSNFE, DTAUTORIZACAO, DTCANCELAMENTO, DTDENEGACAO, DTEMISSAO, DTENTRADA, DTINUTILIZACAO, DTTRANSMISSAO, ESPECIEVOLUME, FRETEPORCONTA, IEPRODUTORRURAL, MARCAVOLUME, MODELO, MODELONFPRODUTORRURAL, MOTIVOCANC, MOTIVOINUT, NUMDOC, NUMDOC2, NUMLOTE, NUMNFPRODUTORRURAL, NUMNOTA, NUMPROTOCOLO, NUMRECIBO, NUMEROVOLUME, OBSERVACAO, PERACRESCIMO, PERDESCONTO, PESOBRUTO, PESOLIQUIDO, SERIE, SERIENFPRODUTORRURAL, STATUS, SUBSERIE, TIPOEMISSAO, TIPOFRETE, TIPOENTRADA, TIPOPAGAMENTO, TOTVOLUME, TPCTE, CODUFPRODUTORRURAL, UTILNUMPROPRIA, VLBASEICMS, VLBASEICMSST, VLCOFINS, VLICMS, VLICMSST, VLIPI, VLPIS, VLSTCOFINS, VLSTPIS, VLACRESCIMO, VLDESCONTO, VLFRETE, VLFRETEFNOTA, VLOUTRASDESP, VLOUTRASFNOTA, VLSEGURO, VLTOTALITENS, VLTOTALNOTA, VLTOTTRIBUTOS, CODCOBRANCA, CODFUNCCANCELAMENTO, CODFUNCINUTILIZACAO, CODFUNCLANCAMENTO, CODCONTA, CODEMPRESA, CODFORNECEDOR, NATOPERACAO, NUMSAIDAORIGEM, CODPLANOPGTO, CODTRANSP, CODVEICULO, MOTIVODEV, VLFCP, VLFCPST, VLFCPSTRET, CODMUNDEST, CODMUNORIG);
-- Table: LOCALIDADE_ESTOQUE
CREATE TABLE LOCALIDADE_ESTOQUE (CODIGO, CODEMPRESA, CODLOCALIDADE, CODPRODUTO, QTBLOQUEADA, QTDISPONIVEL, QTESTOQUE, QTRESERVADA);
-- Table: CARREGAMENTO_COMPLEMENTOS
CREATE TABLE CARREGAMENTO_COMPLEMENTOS (DTFECHMANIF, STATUSMANIF, NUMCARGA, CODVENDMANIF, DTFECHCARGA, SEQENTREGA, CODFUNFECHCARGA);
-- Table: REGIAO
CREATE TABLE REGIAO (CODIGO, NOME, CODROTA, ATIVO);
-- Table: NFENTRADA_COMPLEMENTOS
CREATE TABLE NFENTRADA_COMPLEMENTOS (VLTOTICMSDESON, NUMENTRADA, NUMPEDIDOCOMPRA);
-- Table: LOCALIDADE_ESTOQUE_MOV
CREATE TABLE LOCALIDADE_ESTOQUE_MOV (CODIGO, CODFUNCLANC, CODITEMPED, CODLOCALIDADEEST, CODLOCALIDADEESTORIG, CODMOV, DTMOV, QUANTIDADE, ROTINA, STATUS, TIPOOPERACAO);
-- Table: CTE_NOTA
CREATE TABLE CTE_NOTA (CODCTE, CODNOTA, ID);
-- Table: CARREGAMENTOMDFE
CREATE TABLE CARREGAMENTOMDFE (ID, CODCIDADE, NUMMDFE);
-- Table: REGIAO_COMPLEMENTOS
CREATE TABLE REGIAO_COMPLEMENTOS (CONSIDERAVLMINIMORETIRADA, DIASENTREGA, DIASRETIRADA, VLFRETE, VLMINIMOVENDA, CODREGIAO, DIAENTREGA_DOM, DIAENTREGA_QUA, DIAENTREGA_QUI, DIAENTREGA_SAB, DIAENTREGA_SEG, DIAENTREGA_SEX, DIAENTREGA_TER, DIARETIRADA_DOM, DIARETIRADA_QUA, DIARETIRADA_QUI, DIARETIRADA_SAB, DIARETIRADA_SEG, DIARETIRADA_SEX, DIARETIRADA_TER);
-- Table: NFSAIDA
CREATE TABLE NFSAIDA (NUMSAIDA, CHAVEACESSO, CODCHAVEACESSONFE, CODSTATUSNFE, DTCONTIGENCIA, DESCSTATUSNFE, DTAUTORIZACAO, DTCANCELAMENTO, DTDENEGACAO, DTEMISSAO, DTINUTILIZACAO, DTSAIDA, DTTRANSMISSAO, ESPECIEVOLUME, FRETEPORCONTA, MARCAVOLUME, MODELO, MOTIVOCANC, MOTIVOCONTIGENCIA, MOTIVOINUT, NUMLOTE, NUMNOTA, NUMPROTOCOLO, NUMRECIBO, NUMEROVOLUME, OBSERVACAO, PERDESCONTO, QTITENS, REFANOMESEMISSAONF1A, REFCHAVECTE, REFCHAVENFE, REFCNPJEMITENTENF1A, REFCOOECF, REFMODELOECF, REFMODELONF1A, REFNUMERONF1A, REFORDEMSEQECF, REFSERIENF1A, SERIE, STATUS, TIPOEMISSAO, TIPOFRETE, TIPOOPERACAO, TIPOPAGAMENTO, TOTPESOBRUTO, TOTPESOLIQUIDO, TOTVOLUME, VLCREDCLIENTE, VLFRETE, VLOUTRASDESP, VLSEGURO, VLDESCONTO, VLTOTTRIBESTADUAL, VLTOTTRIBFEDERAL, VLTOTTRIBMUNICIPAL, VLTOTBASEICMS, VLTOTBASEICMSST, VLTOTCOFINS, VLTOTFCPDEST, VLTOTICMS, VLTOTICMSDESON, VLTOTICMSST, VLTOTICMSUFDEST, VLTOTICMSUFREMET, VLTOTIPI, VLTOTITENS, VLTOTNOTA, VLTOTPIS, VLTOTTRIBUTOS, CODCXPDV, NUMCARGA, CODCLIENTE, CODCOBRANCA, CODFUNCCANC, CODFUNCINUTILIZACAO, CODFUNCLANC, CODEMPRESA, CODNATOPERACAO, NUMENTRADAORIGEM, NUMPEDVENDA, NUMPEDIDOORIGEM, CODPLANOPGTO, REFUFEMITENTENF1A, CODTRANSPORTADORA, CODVENDEDOR, VLTROCO, STATUSENVIOCHECKOUT);
-- Table: LOCALIZACAOVEICULO
CREATE TABLE LOCALIZACAOVEICULO (CODIGO, DTLOCALIZACAO, LATITUDE, LONGITUDE, PLACA, RAIO, NUMCARGA);
-- Table: CARTACORRECAO
CREATE TABLE CARTACORRECAO (CODCORRECAO, CHAVEACESSO, CODSTATUS, MSGCORRECAO, DESCSTATUS, DTAUTORIZACAO, DTEMISSAO, NUMLOTE, NUMNOTA, NUMPROTOCOLO, NUMSEQEVENT, TRANSMITIDA, CODFUNCCORRECAO, CODEMPRESA, CODNFEENTRADA, CODNFESAIDA);
-- Table: CTE_VEICULO
CREATE TABLE CTE_VEICULO (CODCTE, CODVEICULO, CODIGO);
-- Table: RELACAOCFOPSAIDAENTRADA
CREATE TABLE RELACAOCFOPSAIDAENTRADA (ID, CFOPENTRADA, CFOPSAIDA, CODEMPRESA);
-- Table: NFSAIDA_COMPLEMENTOS
CREATE TABLE NFSAIDA_COMPLEMENTOS (NUMOP, VLTOTFCPST, VLTOTIRRF, NUMSAIDA);
-- Table: LOCALIZACAOVENDEDOR
CREATE TABLE LOCALIZACAOVENDEDOR (CODIGO, DTLOCALIZACAO, LATITUDE, LONGITUDE, RAIO, CODVENDEDOR);
-- Table: CARTACORRECAOCTE
CREATE TABLE CARTACORRECAOCTE (CODCORRECAO, CHAVEACESSO, CODSTATUS, DESCSTATUS, DTAUTORIZACAO, DTEMISSAO, NUMCTE, NUMLOTE, NUMPROTOCOLO, NUMSEQEVENT, TRANSMITIDA, CODFUNCCORRECAO, CODCTE, CODEMPRESA);
-- Table: CUPOMSITEF
CREATE TABLE CUPOMSITEF (CODIGO, CODAUTORIZA, CODBANDEIRA, CODREDE, CUPOM, DATA, HORA, ISPENDENTE, NSUSITEF, OPERADOR, VALOR, CAIXAPDV, NFCE, DATACANCELAMENTO, HORACANCELAMENTO);
-- Table: NIVEL_CAIXA
CREATE TABLE NIVEL_CAIXA (CODNIVEL, CODCAIXA, CODIGO);
-- Table: LOG_PRECO_ESTOQUE
CREATE TABLE LOG_PRECO_ESTOQUE (ID, CodProduto, CodEmpresa, QtReservadaAntes, QtReservadaDepois, QtBloqueadaAntes, QtBloqueadaDepois, QtDisponivelAntes, QtDisponivelDepois, QtEstoqueAntes, QtEstoqueDepois, QtEstoqueMinimoAntes, QtEstoqueMinimoDepois, QtPendenteAntes, QtPendenteDepois, ColunasAlteradas, HostName, UserName, DateTime, Aplicacao, Mensagem);
-- Table: CATEGORIA
CREATE TABLE CATEGORIA (CODCATEGORIA, DESCRICAO, CODSECAO, DTULTALTERACAO);
-- Table: RELACAOCSOSNSAIDACSTENTRADA
CREATE TABLE RELACAOCSOSNSAIDACSTENTRADA (ID, CSOSNSAIDA, CSTENTRADA, CODEMPRESA);
-- Table: CUSTO
CREATE TABLE CUSTO (CODIGO, NIVEL);
-- Table: NIVEL_EMPRESA
CREATE TABLE NIVEL_EMPRESA (CODNIVEL, CODEMPRESA, CODIGO);
-- Table: LOGALTCABPEDVENDA
CREATE TABLE LOGALTCABPEDVENDA (CODIGO, CODFUNCALT, CODPRODUTO, DTALT, NUMPEDIDO, QTALT, QTPEDIDA, STATUS, TIPOALT);
-- Table: CEST
CREATE TABLE CEST (CODCEST, DESCRICAO, DTULTALTERACAO);
-- Table: CUSTO_ESTOQUE
CREATE TABLE CUSTO_ESTOQUE (ID, CUSTOMANUAL, CUSTOMEDIO, CUSTOULTENTRADA, PRECOCONSUMIDOR, PRECOREVENDA, QTESTBLOQUEADO, QTESTDISPONIVEL, QTESTPENDENTE, QTESTRESERVADO, QTESTOQUE, CODEMPRESA, CODPRODUTO);
-- Table: RELACAOCSTCOFINSSAIDAENTRADA
CREATE TABLE RELACAOCSTCOFINSSAIDAENTRADA (ID, CSTCOFINSENTRADA, CSTCOFINSSAIDA, CODEMPRESA);
-- Table: NIVEL_MOEDA
CREATE TABLE NIVEL_MOEDA (CODNIVEL, CODMOEDA, CODIGO);
-- Table: LOGALTCOB
CREATE TABLE LOGALTCOB (ID, CODCOBRANCA, CODCOBORIGINAL, CODEMPRESA, CODFUNCALT, CODPARCEIRO, ROTORIGEM, DTALT, NUMLANCAMENTO, NUMNOTA, DTVENCALT, DTVENCORIGINAL);
-- Table: CEST_NCM
CREATE TABLE CEST_NCM (CEST, NCM);
-- Table: CUSTO_SUBCUSTO
CREATE TABLE CUSTO_SUBCUSTO (CODCUSTO, CODSUBCUSTO);
-- Table: CFOP
CREATE TABLE CFOP (CODOPERACAO, DESCRICAO, OPERACAO, TIPO);
-- Table: NIVEL_NATUREZA
CREATE TABLE NIVEL_NATUREZA (CODNIVEL, CODNATUREZA, CODIGO);
-- Table: LOGALTCOBPLANOPGTOPERSONALIZADO
CREATE TABLE LOGALTCOBPLANOPGTOPERSONALIZADO (CODIGO, ALTERADO, CODFUNCALT, CODPESSOA, DTALT, ORIGINAL, TIPOALTERACAO);
-- Table: RELACAOCSTIPISAIDAENTRADA
CREATE TABLE RELACAOCSTIPISAIDAENTRADA (ID, CSTIPIENTRADA, CSTIPISAIDA, CODEMPRESA);
-- Table: CXBANCO
CREATE TABLE CXBANCO (CODIGO, ACEITE, AGENCIA, CARTEIRA, CEP, COBREGISTRADA, CODCEDENTE, CODMODCARTEIRA, CODTRANSMISSAO, CONTA, CONVENIO, DVAGENCIA, DVCODCEDENTE, DVCONTA, ENDERECO, FORMACADASTRO, INSTCOB1, INSTCOB2, INSTCOB3, INSTCOB4, INSTCOB5, LAYOUTREM, LOCALPGTO, NOME, NUMDIASINICIAJURO, NUMDIASPROTESTO, PATHBOLETO, PATHREMESSA, PATHRETORNO, PERJURO, PERMULTA, PROXNOSSONUMERO, PROXNUMBORDERO, PROXNUMCH, PROXNUMREM, SEUNUMERO, TIPO, TIPOCOBREM, TIPOCOBRET, TIPOINSCCEDENTE, TPDIST, ULTNUMDOC, VARIACAO, VERSAOLAYOUT, CODBANCO, CODCIDADE, CODEMPRESA, DTULTALT, PERMITEDESC, ATIVO, POSTOSICREDI);
-- Table: CIDADE
CREATE TABLE CIDADE (CODMUNICIPIO, CIDADE, CODESTADO, UF);
-- Table: NIVEL_ROTINA
CREATE TABLE NIVEL_ROTINA (CODNIVEL, CODROTINA, CODIGO);
-- Table: LOGALTCUSTO
CREATE TABLE LOGALTCUSTO (ID, CODEMPRESA, CODFUNCALT, CODPRODUTO, CUSTOMANUALALT, CUSTOMANUALANT, CUSTOMEDIOALT, CUSTOMEDIOANT, CUSTOULTENTRADAALT, CUSTOULTENTRADAANT, DTLALTERACAO, TIPOOPERACAO, NUMENTRADA);
