UPDATE PESSOA2 SET CODIGO = DBO.NUMEROS(CODIGO);
UPDATE PESSOA2 SET ATIVO = CASE WHEN ATIVO IS NULL THEN 1 WHEN TRY_CAST(ATIVO AS INT) IS NOT NULL THEN ATIVO ELSE 1 END;
UPDATE PESSOA2 SET BAIRRO = CASE WHEN LEN(ISNULL(DBO.TRATAR(BAIRRO), '')) > 40 THEN LEFT(DBO.TRATAR(BAIRRO), 40) ELSE ISNULL(DBO.TRATAR(BAIRRO), 'NAO INFORMADO') END,
	BAIRROCOBRANCA = CASE WHEN ISNUMERIC(DBO.TRATAR(BAIRROCOBRANCA)) = 1 THEN LEFT(DBO.TRATAR(BAIRROCOBRANCA), 40) ELSE ISNULL(DBO.TRATAR(BAIRROCOBRANCA), BAIRRO) END,
	BAIRROENTREGA = CASE WHEN ISNUMERIC(DBO.TRATAR(BAIRROENTREGA)) = 1 THEN LEFT(DBO.TRATAR(BAIRROENTREGA), 40) ELSE ISNULL(DBO.TRATAR(BAIRROENTREGA), BAIRRO) END;
UPDATE PESSOA2 SET BLOQATRASO = CASE WHEN BLOQATRASO IN ('0', '1') THEN BLOQATRASO ELSE '0' END,
	BLOQCHD1 = CASE WHEN BLOQCHD1 IN ('0', '1') THEN BLOQCHD1 ELSE '0' END,
	BLOQCHD3 = CASE WHEN BLOQCHD3 IN ('0', '1') THEN BLOQCHD3 ELSE '0' END,
	BLOQCHDV = CASE WHEN BLOQCHDV IN ('0', '1') THEN BLOQCHDV ELSE '0' END,
	BLOQUEADO = CASE WHEN BLOQUEADO IN ('0', '1') THEN BLOQUEADO ELSE '0' END;
UPDATE PESSOA2 SET CATEGORIA = CASE WHEN TRY_CAST(DBO.NUMEROS(CATEGORIA) AS INT) IS NOT NULL THEN LEFT(DBO.NUMEROS(CATEGORIA), 5) ELSE '0' END;
UPDATE PESSOA2 SET CELULAR = CASE WHEN ISNUMERIC(DBO.NUMEROS(CELULAR)) = 1 THEN STUFF(DBO.NUMEROS(CELULAR), 1, 1, '') ELSE '' END,
    CELCOBRANCA = CASE WHEN ISNUMERIC(DBO.NUMEROS(CELCOBRANCA)) = 1 THEN STUFF(DBO.NUMEROS(CELCOBRANCA), 1, 1, '') ELSE '' END,
    CELENTREGA = CASE WHEN ISNUMERIC(DBO.NUMEROS(CELENTREGA)) = 1 THEN STUFF(DBO.NUMEROS(CELENTREGA), 1, 1, '') ELSE '' END;
UPDATE PESSOA2 SET CEP = CASE WHEN LEN(DBO.NUMEROS(ISNULL(CEP, ''))) < 8 THEN DBO.NUMEROS(ISNULL(CEP, '')) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEP, ''))))
	ELSE DBO.NUMEROS(ISNULL(CEP, '75000000')) END;
UPDATE PESSOA2 SET CEPCOBRANCA = CASE WHEN LEN(DBO.NUMEROS(ISNULL(CEPCOBRANCA, ''))) < 8
	THEN DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP)) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP))))
	ELSE DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP)) END;
UPDATE PESSOA2 SET CEPENTREGA = CASE WHEN LEN(DBO.NUMEROS(ISNULL(CEPENTREGA, ''))) < 8
	THEN DBO.NUMEROS(ISNULL(CEPENTREGA, CEP)) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEPENTREGA, CEP))))
	ELSE DBO.NUMEROS(ISNULL(CEPENTREGA, CEP)) END;
UPDATE PESSOA2
SET CNPJ = CASE WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 11 OR LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 14 THEN DBO.NUMEROS(ISNULL(CNPJ, '99999999999'))
	WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 12 THEN '00' + DBO.NUMEROS(ISNULL(CNPJ, '99999999999'))
	WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 13 THEN '0' + DBO.NUMEROS(ISNULL(CNPJ, '99999999999')) ELSE '99999999999' END;
UPDATE PESSOA2 SET COMENTARIO = ISNULL(LEFT(COMENTARIO, 2000), '');
UPDATE PESSOA2 SET COMISSAO = CASE WHEN TRY_CAST(COMISSAO AS DECIMAL(10, 2)) IS NOT NULL THEN LEFT(COMISSAO, 10) ELSE '0' END;
UPDATE PESSOA2 SET COMPLEMENTO = CASE WHEN LEN(ISNULL(COMPLEMENTO, '')) > 40 THEN LEFT(COMPLEMENTO, 40) ELSE ISNULL(COMPLEMENTO, 'SEM COMPLEMENTO') END,
	COMPCOBRANCA = CASE WHEN LEN(ISNULL(COMPCOBRANCA, '')) > 40 THEN LEFT(COMPCOBRANCA, 40) ELSE ISNULL(COMPCOBRANCA, 'SEM COMPLEMENTO') END,
    COMPENTREGA = CASE WHEN LEN(ISNULL(COMPENTREGA, '')) > 40 THEN LEFT(COMPENTREGA, 40) ELSE ISNULL(COMPENTREGA, 'SEM COMPLEMENTO') END;
UPDATE PESSOA2 SET CONTATO = LEFT(DBO.TRATAR(ISNULL(CONTATO, '')), 60);
UPDATE PESSOA2 SET CRC = LEFT(DBO.NUMEROS(ISNULL(CRC, '')), 10);
UPDATE PESSOA2 SET DADOSBANCARIO = LEFT(DBO.TRATAR(ISNULL(DADOSBANCARIO, '')), 200);
UPDATE PESSOA2 SET DTCADASTRO = CASE WHEN DTCADASTRO IS NULL THEN GETDATE() ELSE CONVERT(varchar, DTCADASTRO, 23) END;
UPDATE PESSOA2 SET EMAIL = CASE WHEN ISNULL(EMAIL, '') = '' THEN 'MIGRACAO@EMAIL.COM' ELSE REPLACE(LEFT(EMAIL, 500), ' ', ';') END,
    EMAILBOLETO = CASE WHEN ISNULL(EMAILBOLETO, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
	ELSE REPLACE(LEFT(EMAILBOLETO, 500), ' ', ';') END,
    EMAILCOBRANCA = CASE WHEN ISNULL(EMAILCOBRANCA, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
	ELSE REPLACE(LEFT(EMAILCOBRANCA, 500), ' ', ';') END,
    EMAILENTREGA = CASE WHEN ISNULL(EMAILENTREGA, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
	ELSE REPLACE(LEFT(EMAILENTREGA, 500), ' ', ';') END;
UPDATE PESSOA2 SET MOTIVOBLOQUEIO = CASE WHEN LEN(ISNULL(MOTIVOBLOQUEIO, '')) > 255 THEN LEFT(MOTIVOBLOQUEIO, 255) ELSE ISNULL(MOTIVOBLOQUEIO, '') END;
UPDATE PESSOA2 SET NOME = CASE WHEN NOME IS NULL THEN 'NAO INFORMADO' ELSE DBO.TRATAR(NOME) END;
UPDATE PESSOA2 SET NUMAPOLICE = CASE WHEN LEN(ISNULL(NUMAPOLICE, '')) > 20 THEN LEFT(NUMAPOLICE, 20) ELSE ISNULL(NUMAPOLICE, '') END;
UPDATE PESSOA2 SET NUMAVERBACAO = CASE WHEN LEN(ISNULL(NUMAVERBACAO, '')) > 20 THEN LEFT(NUMAVERBACAO, 20) ELSE ISNULL(NUMAVERBACAO, '') END;
UPDATE PESSOA2 SET NUMCNH = CASE WHEN NUMCNH IS NULL THEN SPACE(20) ELSE DBO.NUMEROS(NUMCNH) END;
UPDATE PESSOA2 SET NUMREGISTRO = CASE WHEN NUMREGISTRO IS NULL THEN SPACE(30) ELSE DBO.NUMEROS(NUMREGISTRO) END;
UPDATE PESSOA2 SET NUMERO = CASE WHEN NUMERO IS NULL THEN '00' ELSE DBO.NUMEROS(NUMERO + '00') END;
UPDATE PESSOA2 SET NUMCOBRANCA = CASE WHEN NUMCOBRANCA IS NULL THEN ISNULL(NUMERO, '00') ELSE DBO.NUMEROS(NUMCOBRANCA) END,
    NUMENTREGA = CASE WHEN NUMENTREGA IS NULL THEN ISNULL(NUMERO, '00') ELSE DBO.NUMEROS(NUMENTREGA) END;
UPDATE PESSOA2 SET PRAZOENTREGA = CASE WHEN PRAZOENTREGA = 0 OR PRAZOENTREGA = 1 THEN PRAZOENTREGA ELSE '0' END;
UPDATE PESSOA2 SET RNTRC = CASE WHEN RNTRC IS NULL THEN SPACE(14) ELSE DBO.NUMEROS(RNTRC) END;
UPDATE PESSOA2 SET SENHA = ISNULL(SENHA, SPACE(80));
UPDATE PESSOA2 SET STATUSALTERACAO = CASE WHEN STATUSALTERACAO = 0 OR STATUSALTERACAO = 1 THEN STATUSALTERACAO ELSE '1' END,
    STATUSFV = CASE WHEN STATUSFV = 0 OR STATUSFV = 1 THEN STATUSFV ELSE '0' END;
UPDATE PESSOA2 SET TELEFONE = CASE WHEN TELEFONE IS NULL THEN '99999999999' 
	ELSE DBO.NUMEROS(CASE WHEN LEFT(TELEFONE, 1) = '0' THEN SUBSTRING(TELEFONE, 2, LEN(TELEFONE)) ELSE TELEFONE END) END,
    TELCOBRANCA = CASE WHEN TELCOBRANCA IS NULL THEN ISNULL(TELEFONE, '99999999999') 
	ELSE DBO.NUMEROS(CASE WHEN LEFT(TELCOBRANCA, 1) = '0' THEN SUBSTRING(TELCOBRANCA, 2, LEN(TELCOBRANCA)) ELSE TELCOBRANCA END) END,
    TELENTREGA = CASE WHEN TELENTREGA IS NULL THEN ISNULL(TELEFONE, '99999999999') 
	ELSE DBO.NUMEROS(CASE WHEN LEFT(TELENTREGA, 1) = '0' THEN SUBSTRING(TELENTREGA, 2, LEN(TELENTREGA)) ELSE TELENTREGA END) END;
UPDATE PESSOA2 SET TIPOMOTORISTA = ISNULL(TIPOMOTORISTA, 'P');
UPDATE PESSOA2 SET TIPOPESSOA = CASE WHEN LEN(CNPJ) = 11 THEN 'F' WHEN LEN(CNPJ) = 14 THEN 'J' ELSE 'P' END;
UPDATE PESSOA2 SET USUARIO = ISNULL(DBO.TRATAR(USUARIO), '');
UPDATE PESSOA2 SET VLCREDDISPONIVEL = ISNULL(STR(ISNULL(VLCREDDISPONIVEL, 0), 20), '0'),
    VLCREDUTILIZADO = ISNULL(STR(ISNULL(VLCREDUTILIZADO, 0), 20), '0'), VLLIMITECRED = ISNULL(STR(ISNULL(VLLIMITECRED, 0), 20), '0');
UPDATE PESSOA2 SET CODCIDADECOBRANCA = ISNULL(CODCIDADECOBRANCA, CODCIDADE),
	CODCIDADEENTREGA = ISNULL(CODCIDADEENTREGA, CODCIDADE),	CODCOBRANCA = ISNULL(CODCOBRANCA, CODCIDADE);
UPDATE PESSOA2 SET COBRANCAPERSONALIZADA = CASE WHEN COBRANCAPERSONALIZADA = 0 OR COBRANCAPERSONALIZADA = 1 THEN COBRANCAPERSONALIZADA ELSE '1' END;
UPDATE PESSOA2 SET CODPLANOPGTO = ISNULL(CODPLANOPGTO, 1),
    CODREGIAO = ISNULL(CODREGIAO, 1),
    CODTABELA = ISNULL(CODTABELA, 1);

