BEGIN
    DECLARE @colunas TABLE (NomeColuna NVARCHAR(100), TipoColuna NVARCHAR(50));
    DECLARE @sql NVARCHAR(MAX) = '';
    INSERT INTO @colunas VALUES
        ('CODIGO', 'INT'),('ATIVO', 'TINYINT'), ('BAIRRO', 'NVARCHAR(40)'), ('BAIRROCOBRANCA', 'NVARCHAR(40)'), ('BAIRROENTREGA', 'NVARCHAR(40)'), ('BLOQATRASO', 'BIT'), 
		('BLOQCHD1', 'BIT'), ('BLOQCHD3', 'BIT'), ('BLOQCHDV', 'BIT'), ('BLOQUEADO', 'BIT'), ('CATEGORIA', 'VARCHAR(5)'), ('CELULAR', 'VARCHAR(30)'), 
		('CELCOBRANCA', 'VARCHAR(30)'), ('CELENTREGA', 'VARCHAR(30)'), ('CEP', 'VARCHAR(8)'), ('CEPCOBRANCA', 'VARCHAR(8)'), ('CEPENTREGA', 'VARCHAR(8)'), 
		('CNPJ', 'VARCHAR(14)'), ('COMENTARIO', 'VARCHAR(2000)'), ('COMISSAO', 'NUMERIC(20,6)'), ('COMPLEMENTO', 'VARCHAR(40)'), ('COMPCOBRANCA', 'VARCHAR(40)'), 
        ('COMPENTREGA', 'VARCHAR(40)'), ('CONTATO', 'VARCHAR(600)'), ('CRC', 'VARCHAR(10)'), ('DADOSBANCARIO', 'VARCHAR(200)'), ('DTADMISSAO', 'DATETIME2(7)'), 
		('DTBLOQUEIO', 'DATETIME2(7)'), ('DTCADASTRO', 'DATETIME2(7)'), ('DTNASCIMENTO', 'DATETIME2(7)'), ('DTULTALTERACAO', 'DATETIME2(7)'), 
		('DTULTCOMPRA', 'DATETIME2(7)'), ('DTVENCIMENTO', 'DATETIME2(7)'), ('EMAIL', 'VARCHAR(500)'), ('EMAILBOLETO', 'VARCHAR(500)'), ('EMAILCOBRANCA', 'VARCHAR(500)'), 
		('EMAILENTREGA', 'VARCHAR(500)'), ('ENDERECO', 'VARCHAR(60)'), ('ENDCOBRANCA', 'VARCHAR(60)'), ('ENDENTREGA', 'VARCHAR(60)'), ('FANTASIA', 'VARCHAR(60)'), 
		('ISUF', 'VARCHAR(9)'), ('IDESTRANGEIRO', 'VARCHAR(20)'), ('IE', 'VARCHAR(20)'), ('ISCLIENTE', 'BIT'), ('ISCOLABORADOR', 'BIT'), ('ISFORNECEDOR', 'BIT'), 
		('ISMOTORISTA', 'BIT'), ('ISTRANSPORTADORA', 'BIT'), ('JUROS', 'NUMERIC(20,6)'), ('MOTIVOBLOQUEIO', 'VARCHAR(255)'), ('NOME', 'VARCHAR(60)'), 
		('NUMAPOLICE', 'VARCHAR(20)'), ('NUMAVERBACAO', 'VARCHAR(20)'), ('NUMCNH', 'VARCHAR(20)'), ('NUMREGISTRO', 'VARCHAR(30)'), ('NUMERO', 'VARCHAR(11)'), 
		('NUMCOBRANCA', 'VARCHAR(11)'), ('NUMENTREGA', 'VARCHAR(11)'), ('PRAZOENTREGA', 'INT'), ('RNTRC', 'VARCHAR(14)'), ('SENHA', 'VARCHAR(80)'), ('STATUSALTERACAO', 'BIT'), 
		('STATUSFV', 'BIT'), ('TELEFONE', 'VARCHAR(30)'), ('TELCOBRANCA', 'VARCHAR(30)'), ('TELENTREGA', 'VARCHAR(30)'), ('TIPOMOTORISTA', 'VARCHAR(1)'), 
		('TIPOPESSOA', 'VARCHAR(1)'), ('USUARIO', 'VARCHAR(20)'), ('VLCREDDISPONIVEL', 'NUMERIC(20,6)'), ('VLCREDUTILIZADO', 'NUMERIC(20,6)'), 
		('VLLIMITECRED', 'NUMERIC(20,6)'), ('CODCIDADE', 'INT'), ('TempCODCIDADE', 'INT'), ('CODCIDADECOBRANCA', 'INT'), ('CODCIDADEENTREGA', 'INT'), ('CODCOBRANCA', 'VARCHAR(255)'), 
		('CODRAMOATIVIDADE', 'INT'), ('CODEMPRESA', 'INT'), ('CODNIVELACESSO', 'INT'), ('CODPLANOPGTO', 'INT'), ('CODREGIAO', 'INT'), ('CODSEGNIVELACESSO', 'INT'), 
		('CODSETOR', 'INT'), ('CODTABELA', 'INT'), ('TIPOCALCULO', 'NVARCHAR(50)'), ('CODVENDEDOR', 'INT'), ('CODVENDEDOR2', 'INT'), ('CODVENDEDOR3', 'INT'), 
		('CODVENDEDOR4', 'INT'), ('COBRANCAPERSONALIZADA', 'TINYINT'), ('LATITUDE', 'DECIMAL(10,8)'), ('LONGITUDE', 'DECIMAL(10,8)');
    SELECT @sql = @sql + 
        CASE 
            WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PESSOA2' AND COLUMN_NAME = c.NomeColuna) 
                THEN ''
            ELSE 'ALTER TABLE PESSOA2 ADD ' + QUOTENAME(c.NomeColuna) + ' ' + c.TipoColuna + '; '
        END
    FROM @colunas c;
    EXEC sp_executesql @sql;
END
GO

BEGIN
	BEGIN
		UPDATE PESSOA2 
		SET FANTASIA = LEFT((ISNULL(DBO.TRATAR(FANTASIA), ISNULL(DBO.TRATAR(NOME), 'NAO INFORMADO'))), 60)
	END;
	BEGIN
		IF EXISTS (SELECT 1 FROM PESSOA2 WHERE CODIGO IS NULL)
		BEGIN
			;WITH CTE AS (
				SELECT CODIGO,
					ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS RowNumber
				FROM PESSOA2
				WHERE CODIGO IS NULL)
			UPDATE CTE SET CODIGO = RowNumber;
		END
		ELSE
		BEGIN
			UPDATE PESSOA2 SET CODIGO = DBO.NUMEROS(CODIGO);
		END
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ATIVO = CASE 
				WHEN ATIVO IS NULL THEN 1 
				WHEN TRY_CAST(ATIVO AS INT) IS NOT NULL THEN ATIVO 
					ELSE 1 END;
	END;
	BEGIN
		UPDATE PESSOA2
			SET NOME = LEFT(NOME, 60)
	END;
	BEGIN
		UPDATE PESSOA2
			SET IE = DBO.NUMEROS(IE)
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BAIRRO = CASE 
				WHEN LEN(ISNULL(DBO.TRATAR(BAIRRO), '')) > 40 THEN LEFT(DBO.TRATAR(BAIRRO), 40) 
					ELSE ISNULL(DBO.TRATAR(BAIRRO), 'NAO INFORMADO') END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET	BAIRROCOBRANCA = CASE 
				WHEN ISNUMERIC(DBO.TRATAR(BAIRROCOBRANCA)) = 1 THEN LEFT(DBO.TRATAR(BAIRROCOBRANCA), 40) 
					ELSE ISNULL(DBO.TRATAR(BAIRROCOBRANCA), BAIRRO) END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET	BAIRROENTREGA = CASE 
				WHEN ISNUMERIC(DBO.TRATAR(BAIRROENTREGA)) = 1 THEN LEFT(DBO.TRATAR(BAIRROENTREGA), 40) 
					ELSE ISNULL(DBO.TRATAR(BAIRROENTREGA), BAIRRO) END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BLOQATRASO = CASE 
				WHEN BLOQATRASO IN ('0', '1') THEN BLOQATRASO 
					ELSE '0' END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BLOQCHD1 = CASE 
				WHEN BLOQCHD1 IN ('0', '1') THEN BLOQCHD1 
					ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BLOQCHD3 = CASE 
				WHEN BLOQCHD3 IN ('0', '1') THEN BLOQCHD3 
					ELSE '0' END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BLOQCHDV = CASE 
				WHEN BLOQCHDV IN ('0', '1') THEN BLOQCHDV 
					ELSE '0' END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET BLOQUEADO = CASE 
				WHEN BLOQUEADO IN ('0', '1') THEN BLOQUEADO 
					ELSE '0' END; 
	END;
	BEGIN
		UPDATE PESSOA2
			SET CATEGORIA = CASE
				WHEN DBO.NUMEROS(CATEGORIA) IS NOT NULL AND LEN(DBO.NUMEROS(CATEGORIA)) > 5 THEN LEFT(DBO.NUMEROS(CATEGORIA), 5)
					ELSE '' END;
	END;
	BEGIN
		UPDATE PESSOA2 SET TELEFONE = DBO.NUMEROS(LTRIM(RTRIM(TELEFONE)))
	END;
	BEGIN
		UPDATE PESSOA2 SET TELCOBRANCA = DBO.NUMEROS(LTRIM(RTRIM(TELCOBRANCA)))
	END;
	BEGIN
		UPDATE PESSOA2 SET TELENTREGA = DBO.NUMEROS(LTRIM(RTRIM(TELCOBRANCA)))
	END;
	BEGIN
		UPDATE PESSOA2 
			SET TELEFONE = CASE 
				WHEN TELEFONE IS NULL THEN '99999999999'
				WHEN TELEFONE = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(TELEFONE, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(TELEFONE, '')))) + DBO.NUMEROS(ISNULL(TELEFONE, ''))
				WHEN LEFT(TELEFONE, 2) = '55' OR LEN(TELEFONE) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELEFONE)), 3, LEN(LTRIM(RTRIM(TELEFONE))) - 2))
				WHEN LEFT(TELEFONE, 1) = '0' OR LEN(TELEFONE) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELEFONE)), 2, LEN(LTRIM(RTRIM(TELEFONE)))))
					ELSE TELEFONE END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET TELCOBRANCA = CASE 
				WHEN TELCOBRANCA = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(TELCOBRANCA, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(TELCOBRANCA, '')))) + DBO.NUMEROS(ISNULL(TELCOBRANCA, ''))
				WHEN LEFT(TELCOBRANCA, 2) = '55' OR LEN(TELCOBRANCA) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELCOBRANCA)), 3, LEN(LTRIM(RTRIM(TELCOBRANCA))) - 2))
				WHEN LEFT(TELCOBRANCA, 1) = '0' OR LEN(TELCOBRANCA) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELCOBRANCA)), 2, LEN(LTRIM(RTRIM(TELCOBRANCA)))))
					ELSE TELEFONE END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET TELENTREGA = CASE 
				WHEN TELENTREGA = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(TELENTREGA, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(TELENTREGA, '')))) + DBO.NUMEROS(ISNULL(TELENTREGA, ''))
				WHEN LEFT(TELENTREGA, 2) = '55' OR LEN(TELENTREGA) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELENTREGA)), 3, LEN(LTRIM(RTRIM(TELENTREGA))) - 2))
				WHEN LEFT(TELENTREGA, 1) = '0' OR LEN(TELENTREGA) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(TELENTREGA)), 2, LEN(LTRIM(RTRIM(TELENTREGA)))))
					ELSE TELEFONE END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CELULAR = CASE 
				WHEN LEN(ISNULL(CELULAR, '')) = 11 AND ISNUMERIC(DBO.NUMEROS(CELULAR)) = 1 THEN DBO.NUMEROS(CELULAR)
				WHEN LEN(ISNULL(CELULAR, '')) > 11 AND ISNUMERIC(DBO.NUMEROS(CELULAR)) = 1 THEN STUFF(DBO.NUMEROS(CELULAR), 1, PATINDEX('%[^0]%', DBO.NUMEROS(CELULAR)) - 1, '')
					ELSE CELULAR END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CELULAR = CASE 
				WHEN CELULAR = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(CELULAR, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(CELULAR, '')))) + DBO.NUMEROS(ISNULL(CELULAR, ''))
				WHEN LEFT(CELULAR, 2) = '55' OR LEN(CELULAR) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELULAR)), 3, LEN(LTRIM(RTRIM(CELULAR))) - 2))
				WHEN LEFT(CELULAR, 1) = '0' OR LEN(CELULAR) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELULAR)), 2, LEN(LTRIM(RTRIM(CELULAR)))))
					ELSE CELULAR END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CELCOBRANCA = CASE 
				WHEN CELCOBRANCA = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(CELCOBRANCA, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(CELCOBRANCA, '')))) + DBO.NUMEROS(ISNULL(CELCOBRANCA, ''))
				WHEN LEFT(CELCOBRANCA, 2) = '55' OR LEN(CELCOBRANCA) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELCOBRANCA)), 3, LEN(LTRIM(RTRIM(CELCOBRANCA))) - 2))
				WHEN LEFT(CELCOBRANCA, 1) = '0' OR LEN(CELCOBRANCA) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELCOBRANCA)), 2, LEN(LTRIM(RTRIM(CELCOBRANCA)))))
					ELSE CELULAR END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CELENTREGA = CASE 
				WHEN CELENTREGA = '' THEN '99999999999'
				WHEN LEN(DBO.NUMEROS(ISNULL(CELENTREGA, ''))) < 9 THEN '9' + REPLICATE('9', 9 - LEN(DBO.NUMEROS(ISNULL(CELENTREGA, '')))) + DBO.NUMEROS(ISNULL(CELENTREGA, ''))
				WHEN LEFT(CELENTREGA, 2) = '55' OR LEN(CELENTREGA) = 13 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELENTREGA)), 3, LEN(LTRIM(RTRIM(CELENTREGA))) - 2))
				WHEN LEFT(CELENTREGA, 1) = '0' OR LEN(CELENTREGA) = 12 THEN DBO.NUMEROS(SUBSTRING(LTRIM(RTRIM(CELENTREGA)), 2, LEN(LTRIM(RTRIM(CELENTREGA)))))
					ELSE TELEFONE END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CEP = CASE 
				WHEN LEN(DBO.NUMEROS(ISNULL(CEP, ''))) < 8 THEN DBO.NUMEROS(ISNULL(CEP, '')) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEP, '')))) 
					ELSE DBO.NUMEROS(ISNULL(CEP, (SELECT TOP 1 E.CEP FROM EMPRESA E))) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CEPCOBRANCA = CASE 
				WHEN LEN(DBO.NUMEROS(ISNULL(CEPCOBRANCA, ''))) < 8 THEN DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP)) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP)))) 
					ELSE DBO.NUMEROS(ISNULL(CEPCOBRANCA, CEP)) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CEPENTREGA = CASE 
				WHEN LEN(DBO.NUMEROS(ISNULL(CEPENTREGA, ''))) < 8 THEN DBO.NUMEROS(ISNULL(CEPENTREGA, CEP)) + REPLICATE('0', 8 - LEN(DBO.NUMEROS(ISNULL(CEPENTREGA, CEP)))) 
					ELSE DBO.NUMEROS(ISNULL(CEPENTREGA, CEP)) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CNPJ = CASE 
				WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 11 OR LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 14 THEN DBO.NUMEROS(ISNULL(CNPJ, '99999999999')) 
				WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 12 THEN '00' + DBO.NUMEROS(ISNULL(CNPJ, '99999999999')) 
				WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) = 13 THEN '0' + DBO.NUMEROS(ISNULL(CNPJ, '99999999999'))
				WHEN LEN(DBO.NUMEROS(ISNULL(CNPJ, ''))) > 14 then LEFT(CNPJ, 14)
					ELSE '99999999999' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COMENTARIO = ISNULL(LEFT(COMENTARIO, 2000), '');
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COMISSAO = CASE 
				WHEN TRY_CAST(COMISSAO AS DECIMAL(10, 2)) IS NOT NULL THEN LEFT(COMISSAO, 10) 
					ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COMPLEMENTO = CASE 
				WHEN LEN(ISNULL(COMPLEMENTO, '')) > 40 THEN LEFT(DBO.TRATAR(COMPLEMENTO), 40)
					ELSE ISNULL(DBO.TRATAR(COMPLEMENTO), 'SEM COMPLEMENTO') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COMPCOBRANCA = CASE 
				WHEN LEN(ISNULL(COMPCOBRANCA, '')) > 40 THEN LEFT(DBO.TRATAR(COMPCOBRANCA), 40) 
					ELSE ISNULL(DBO.TRATAR(COMPCOBRANCA), DBO.TRATAR(COMPLEMENTO)) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COMPENTREGA = CASE 
				WHEN LEN(ISNULL(COMPENTREGA, '')) > 40 THEN LEFT(DBO.TRATAR(COMPENTREGA), 40) 
					ELSE ISNULL(DBO.TRATAR(COMPENTREGA), DBO.TRATAR(COMPLEMENTO)) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CONTATO = LEFT(ISNULL(DBO.TRATAR(CONTATO), NULL), 60);
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CRC = LEFT(DBO.NUMEROS(ISNULL(CRC, '')), 10);
	END;
	BEGIN
		UPDATE PESSOA2 
			SET DADOSBANCARIO = LEFT(DBO.TRATAR(ISNULL(DADOSBANCARIO, '')), 200);
	END;
	BEGIN
		UPDATE PESSOA2 
			SET DTCADASTRO = ISNULL(DTCADASTRO, CONVERT(DATETIME2(7),GETDATE()));
	END;
	BEGIN
		UPDATE PESSOA2 
			SET EMAIL = CASE 
				WHEN ISNULL(EMAIL, '') = '' THEN 'MIGRACAO@EMAIL.COM' 
					ELSE REPLACE(LEFT(EMAIL, 500), ' ', ';') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET EMAILBOLETO = CASE 
				WHEN ISNULL(EMAILBOLETO, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
					ELSE REPLACE(LEFT(EMAILBOLETO, 500), ' ', ';') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET EMAILCOBRANCA = CASE 
				WHEN ISNULL(EMAILCOBRANCA, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
					ELSE REPLACE(LEFT(EMAILCOBRANCA, 500), ' ', ';') END; 
	END;
	BEGIN
		UPDATE PESSOA2 
			SET EMAILENTREGA = CASE 
				WHEN ISNULL(EMAILENTREGA, '') = '' THEN REPLACE(LEFT(ISNULL(EMAIL, 'MIGRACAO@EMAIL.COM'), 500), ' ', ';')
					ELSE REPLACE(LEFT(EMAILENTREGA, 500), ' ', ';') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET MOTIVOBLOQUEIO = CASE 
				WHEN LEN(ISNULL(MOTIVOBLOQUEIO, '')) > 255 THEN LEFT(DBO.TRATAR(MOTIVOBLOQUEIO), 255) 
					ELSE ISNULL(DBO.TRATAR(MOTIVOBLOQUEIO), NULL) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMAPOLICE = CASE 
				WHEN LEN(ISNULL(NUMAPOLICE, '')) > 20 THEN LEFT(NUMAPOLICE, 20) 
					ELSE ISNULL(NUMAPOLICE, '') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMAVERBACAO = CASE 
				WHEN LEN(ISNULL(NUMAVERBACAO, '')) > 20 THEN LEFT(NUMAVERBACAO, 20) 
					ELSE ISNULL(NUMAVERBACAO, '') END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMCNH = CASE 
				WHEN NUMCNH IS NULL THEN '' 
					ELSE DBO.NUMEROS(NUMCNH) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMREGISTRO = CASE 
				WHEN NUMREGISTRO IS NULL THEN '' 
					ELSE DBO.NUMEROS(NUMREGISTRO) END;
	END;
		BEGIN
			UPDATE PESSOA2 
				SET NUMERO = CASE 
					WHEN NUMERO IS NULL THEN '00' 
						ELSE DBO.NUMEROS(NUMERO) END;
		END;
		BEGIN
			UPDATE PESSOA2 
				SET NUMCOBRANCA = CASE 
					WHEN NUMCOBRANCA IS NULL THEN ISNULL(DBO.NUMEROS(NUMERO), '00') 
						ELSE DBO.NUMEROS(NUMCOBRANCA)  END;
		END;
		BEGIN
			UPDATE PESSOA2 
				SET NUMENTREGA = CASE 
					WHEN NUMENTREGA IS NULL THEN ISNULL(DBO.NUMEROS(NUMERO), '00') 
						ELSE DBO.NUMEROS(NUMENTREGA) END;
		END;
	BEGIN
		UPDATE PESSOA2 
			SET PRAZOENTREGA = CASE 
				WHEN PRAZOENTREGA = 0 OR PRAZOENTREGA = 1 THEN PRAZOENTREGA 
					ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET RNTRC = CASE 
				WHEN RNTRC IS NULL THEN SPACE(1) 
					ELSE DBO.NUMEROS(RNTRC) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET SENHA = ISNULL(SENHA, SPACE(1));
	END;
	BEGIN
		UPDATE PESSOA2 
			SET STATUSALTERACAO = CASE 
				WHEN STATUSALTERACAO = 0 OR STATUSALTERACAO = 1 THEN STATUSALTERACAO 
					ELSE '1' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET STATUSFV = CASE 
				WHEN STATUSFV = 0 OR STATUSFV = 1 THEN STATUSFV 
					ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET TIPOMOTORISTA = CASE 
				WHEN TIPOMOTORISTA = 'P' OR TIPOMOTORISTA = 'T' THEN TIPOMOTORISTA 
					ELSE 'P' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET TIPOPESSOA = CASE 
				WHEN LEN(CNPJ) = 11 THEN 'F' 
				WHEN LEN(CNPJ) = 14 THEN 'J' 
					ELSE 'P' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET USUARIO = ISNULL(DBO.TRATAR(USUARIO), '');
	END;
	BEGIN
		UPDATE PESSOA2 
			SET VLCREDDISPONIVEL = ISNULL(STR(ISNULL(VLCREDDISPONIVEL, 0), 20), '0')
	END;
	BEGIN
		UPDATE PESSOA2 
			SET VLCREDUTILIZADO = ISNULL(STR(ISNULL(VLCREDUTILIZADO, 0), 20), '0')
	END;
	BEGIN
		UPDATE PESSOA2 
			SET VLLIMITECRED = ISNULL(STR(ISNULL(VLLIMITECRED, 0), 20), '0')
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COBRANCAPERSONALIZADA = CASE
				WHEN COBRANCAPERSONALIZADA = 0 OR COBRANCAPERSONALIZADA = 1 THEN COBRANCAPERSONALIZADA 
					ELSE 0 END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODREGIAO = ISNULL(CODREGIAO, 1)
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODTABELA = ISNULL(CODTABELA, 1);
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ISCLIENTE = CASE 
				WHEN ISCLIENTE IN ('0', '1') THEN ISCLIENTE
					WHEN ISCLIENTE LIKE '%SIM%' THEN '1'
						WHEN DBO.TRATAR(ISCLIENTE) LIKE '%NAO%' THEN '0'
							ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ISCOLABORADOR = CASE 
				WHEN ISCOLABORADOR IN ('0', '1') THEN ISCOLABORADOR
					WHEN ISCOLABORADOR LIKE '%SIM%' THEN '1'
						WHEN DBO.TRATAR(ISCOLABORADOR) LIKE '%NAO%' THEN '0'
							ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ISFORNECEDOR = CASE 
				WHEN ISFORNECEDOR IN ('0', '1') THEN ISFORNECEDOR
					WHEN ISFORNECEDOR LIKE '%SIM%' THEN '1'
						WHEN DBO.TRATAR(ISFORNECEDOR) LIKE '%NAO%' THEN '0'
							ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ISMOTORISTA = CASE 
				WHEN ISMOTORISTA IN ('0', '1') THEN ISMOTORISTA
					WHEN ISMOTORISTA LIKE '%SIM%' THEN '1'
						WHEN DBO.TRATAR(ISMOTORISTA) LIKE '%NAO%' THEN '0'
							ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ISTRANSPORTADORA = CASE 
				WHEN ISTRANSPORTADORA IN ('0', '1') THEN ISTRANSPORTADORA
					WHEN ISTRANSPORTADORA LIKE '%SIM%' THEN '1'
						WHEN DBO.TRATAR(ISTRANSPORTADORA) LIKE '%NAO%' THEN '0'
							ELSE '0' END;
	END;
	BEGIN
		UPDATE PESSOA2 SET CEP = (SELECT CEP FROM EMPRESA WHERE CODIGO = 1) WHERE CEP IN ('00000000','75000000')
	END
	BEGIN 
		UPDATE PESSOA2
			SET TIPOCALCULO = CASE 
				WHEN LEN(CNPJ) = 14 AND IE <> 'ISENTO' THEN 2
				WHEN LEN(CNPJ) = 14 AND IE = 'ISENTO' THEN 1
				WHEN LEN(CNPJ) = 11 AND IE = 'ISENTO' THEN 1
				WHEN LEN(CNPJ) = 11 AND IE <> 'ISENTO' AND IE IS NOT NULL THEN 1
					ELSE TIPOCALCULO END;
	END;
	BEGIN
		IF NOT EXISTS (SELECT DESCRICAO FROM RAMOATIVIDADE WHERE ID IN (SELECT CODRAMOATIVIDADE FROM PESSOA2))
		BEGIN
			INSERT INTO RAMOATIVIDADE (DESCRICAO)
			SELECT DISTINCT CODRAMOATIVIDADE FROM PESSOA2 WHERE CODRAMOATIVIDADE IS NOT NULL AND ISNUMERIC(CODRAMOATIVIDADE) = 0;
		END;
		BEGIN
			UPDATE PESSOA2
			SET CODRAMOATIVIDADE = B.ID
			FROM PESSOA2 P
			INNER JOIN RAMOATIVIDADE B ON P.CODRAMOATIVIDADE = B.DESCRICAO;
		END;
	END;
	/*BEGIN
		IF NOT EXISTS (SELECT NOME FROM VENDEDOR WHERE NOME IN (SELECT CODVENDEDOR FROM PESSOA2))
			BEGIN
				INSERT INTO VENDEDOR (NOME)
				SELECT DISTINCT CODVENDEDOR FROM PESSOA2 WHERE ISNUMERIC(CODVENDEDOR) = 0;
			END;
		BEGIN
			UPDATE VENDEDOR SET BAIRRO = '', CELULAR = '',CEP = '', CNPJCPF = '', COMPLEMENTO = '', DTCADASTRO = CONVERT(DATETIME2(7),GETDATE()),
			DTULTALTERACAO = CONVERT(DATETIME2(7),GETDATE()), EMAIL = '', ENDERECO = '', NUMERO = 0, PERCOMISSAO = 0, RG = '', TELEFONE = '',
			TIPOCOMISSAO = 'CPA',CODCIDADE = (SELECT CODCIDADE FROM EMPRESA WHERE CODIGO = 1) 
					WHERE CNPJCPF IS NULL AND CODCIDADE IS NULL
		END;
		BEGIN
			INSERT INTO VENDEDOR_COMPLEMENTOS (CODVENDEDOR) 
			SELECT CODIGO FROM VENDEDOR WHERE CODIGO NOT IN (SELECT CODVENDEDOR FROM VENDEDOR_COMPLEMENTOS)
		END;
		BEGIN
			UPDATE PESSOA2
			SET CODVENDEDOR = B.CODIGO
			FROM PESSOA2 P
			INNER JOIN VENDEDOR B ON P.CODVENDEDOR = B.NOME;
		END;
	END;*/
	BEGIN
		UPDATE PESSOA2 SET CODVENDEDOR = 1 WHERE CODVENDEDOR IS NULL
	END;
	BEGIN
		UPDATE PESSOA2
			SET ENDERECO = CASE 
				WHEN LEN(ISNULL(ENDERECO, '')) > 60 THEN LEFT(DBO.TRATAR(ENDERECO), 60)
					WHEN ENDERECO IS NULL THEN 'NAO INFORMADO'
						ELSE DBO.TRATAR(ENDERECO) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ENDCOBRANCA = CASE 
				WHEN LEN(ISNULL(ENDCOBRANCA, '')) > 60 THEN LEFT(DBO.TRATAR(ENDCOBRANCA), 60)
				WHEN ENDCOBRANCA IS NULL THEN DBO.TRATAR(ISNULL(ENDERECO, 'NAO INFORMADO'))
					ELSE DBO.TRATAR(ENDCOBRANCA) END;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET ENDENTREGA = CASE 
				WHEN LEN(ISNULL(ENDENTREGA, '')) > 60 THEN LEFT(DBO.TRATAR(ENDENTREGA), 60)
				WHEN ENDENTREGA IS NULL THEN DBO.TRATAR(ISNULL(ENDCOBRANCA, ISNULL(ENDERECO, 'NAO INFORMADO')))
					ELSE DBO.TRATAR(ENDENTREGA)END;
	END;
	BEGIN
		UPDATE PESSOA2
			SET LATITUDE = ISNULL(LATITUDE, 0),
				LONGITUDE = ISNULL(LONGITUDE, 0);
	END;
END;
GO

/*
BEGIN
	CREATE TABLE #TempPESSOA (CODIGO INT,NOME VARCHAR(100),IE VARCHAR(20),UF VARCHAR(2),CODMUNICIPIO INT);
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 8 AND B.CODESTADO IN (29,33) AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 9 AND B.CODESTADO IN (13,14,15,16,26,21,22,23,25,27,28,32,42,50,52) AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 10 AND B.CODESTADO IN (41,43) AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 11 AND B.CODESTADO IN (17,51) AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 12 AND B.CODESTADO = 35 AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) <> 13 AND B.CODESTADO IN (12,31,53) AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) NOT IN (9,14) AND B.CODESTADO = 11 AND A.IE <> 'ISENTO';
	INSERT INTO #TempPESSOA (CODIGO, NOME, IE, UF, CODMUNICIPIO)
		SELECT A.CODIGO, A.NOME, A.IE, B.UF, B.CODMUNICIPIO FROM PESSOA A
		INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO
		WHERE LEN(A.IE) NOT IN (9,10) AND B.CODESTADO = 24 AND A.IE <> 'ISENTO';
END;
GO
*/

BEGIN
	BEGIN
		UPDATE P2
			SET CODCIDADE = C.CODMUNICIPIO
				FROM PESSOA2 P2
				INNER JOIN CIDADE C
					ON P2.CODCIDADE = C.CIDADE;
	END;
	BEGIN
		UPDATE P2
			SET CODCIDADE = C.CODMUNICIPIO
				FROM PESSOA2 P2
				INNER JOIN CIDADE C
					ON DBO.TRATAR(P2.CODCIDADE) = DBO.TRATAR(C.CIDADE)
						WHERE P2.CODCIDADE IS NULL;
	END;
	BEGIN
		UPDATE P2
			SET CODCIDADE = C.CODMUNICIPIO
				FROM PESSOA2 P2
				INNER JOIN CIDADE C
					ON SOUNDEX(P2.CODCIDADE) = SOUNDEX(C.CIDADE)
					AND DIFFERENCE(P2.CODCIDADE, C.CIDADE) >= 3
						WHERE P2.CODCIDADE IS NULL;
	END;
	BEGIN
		UPDATE P2
			SET P2.CODCIDADE = CODCIDADE
				FROM PESSOA2 P2;
	END;
END;
GO

BEGIN
	BEGIN
		UPDATE PESSOA2 
			SET IE = 'ISENTO' WHERE IE IS NULL;
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODCIDADE = (SELECT CODCIDADE FROM EMPRESA WHERE CODIGO = 1) WHERE ISNUMERIC(CODCIDADE) = 0
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CEP = (SELECT CEP FROM EMPRESA WHERE CODIGO = 1) WHERE CEP IS NULL
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODCIDADE = (SELECT CODCIDADE FROM EMPRESA WHERE CODIGO = 1) WHERE CODCIDADE IS NULL
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMCOBRANCA = 0 WHERE NUMCOBRANCA = ''
	END;
	BEGIN
		UPDATE PESSOA2 
			SET NUMENTREGA = 0 WHERE NUMENTREGA = ''
	END;
	BEGIN
		UPDATE PESSOA2 
			SET COBRANCAPERSONALIZADA = ISNULL(COBRANCAPERSONALIZADA, 0)
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODCIDADECOBRANCA = ISNULL(CODCIDADECOBRANCA, CODCIDADE)
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODCIDADEENTREGA = ISNULL(CODCIDADEENTREGA, CODCIDADE);
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODIGO = (SELECT MAX(CODIGO) FROM PESSOA2) + 1 WHERE CODIGO = 1
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODIGO = (SELECT MAX(CODIGO) FROM PESSOA2) + 1 WHERE CODIGO = 10000
	END;
	BEGIN
		UPDATE PESSOA2 
			SET CODIGO = (SELECT MAX(CODIGO) FROM PESSOA2) + 1 WHERE CODIGO = 20000
	END;
END;
GO

/*
BEGIN
	SET IDENTITY_INSERT PESSOA ON

	DECLARE @colunas NVARCHAR(MAX) = '';
	DECLARE @insertSQL NVARCHAR(MAX) = '';
	DECLARE @tableOrigem NVARCHAR(128) = 'PESSOA2';
	DECLARE @tableDestino NVARCHAR(128) = 'PESSOA';

	SELECT @colunas = STRING_AGG(COLUMN_NAME, ', ')
	FROM (
		SELECT c.COLUMN_NAME
		FROM INFORMATION_SCHEMA.COLUMNS c
		JOIN INFORMATION_SCHEMA.COLUMNS d
			ON c.COLUMN_NAME = d.COLUMN_NAME
		WHERE c.TABLE_NAME = @tableOrigem
		  AND d.TABLE_NAME = @tableDestino
	) AS ColunasComuns;

	IF @colunas IS NOT NULL AND LEN(@colunas) > 0
	BEGIN

		SET @insertSQL = 'INSERT INTO ' + @tableDestino + ' (' + @colunas + ') ' +
						 'SELECT ' + @colunas + ' FROM ' + @tableOrigem;

		EXEC sp_executesql @insertSQL;
		PRINT 'Dados inseridos com sucesso nas colunas: ' + @colunas;
	END
	ELSE
	BEGIN
		PRINT 'Nenhuma coluna em comum encontrada entre as tabelas ' + @tableOrigem + ' e ' + @tableDestino;
	END;
	SET IDENTITY_INSERT PESSOA OFF
END;
GO

BEGIN
	INSERT INTO PESSOA_COMPLEMENTOS (ISCONTRIBUINTE,CODPESSOA)
	SELECT IIF(IE = 'ISENTO',0,1),CODIGO
	FROM PESSOA WHERE CODIGO NOT IN (SELECT CODPESSOA FROM PESSOA_COMPLEMENTOS)
END;
GO
*/

--SELECT * FROM PESSOA2