SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 8 AND B.CODESTADO IN (29,33) AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 9 AND B.CODESTADO IN (13,14,15,16,26,21,22,23,25,27,28,32,42,50,52) AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 10 AND B.CODESTADO IN (41,43) AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 11 AND B.CODESTADO IN (17,51) AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 12 AND B.CODESTADO = 35 AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) <> 13 AND B.CODESTADO IN (12,31,53) AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) NOT IN (9,14)  AND B.CODESTADO = 11 AND A.IE <> 'ISENTO'

SELECT A.CODIGO,A.NOME,A.IE,B.UF,B.CODMUNICIPIO FROM PESSOA A
INNER JOIN CIDADE B ON A.CODCIDADE = B.CODMUNICIPIO WHERE LEN(A.IE) NOT IN (9,10)  AND B.CODESTADO = 24 AND A.IE <> 'ISENTO'